In [11]:
import sys

print(sys.executable)
print(sys.version)
print("\nPython Paths:\n")
for path in sys.path:
    print(path)
print("\n")

!{sys.executable} -m pip install -U python-woc pandas matplotlib

/usr/bin/python3.11
3.11.13 (main, Jun  1 2026, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-14)]

Python Paths:

/usr/lib64/python311.zip
/usr/lib64/python3.11
/usr/lib64/python3.11/lib-dynload

/home/cdamron3/.local/lib/python3.11/site-packages
/usr/lib64/python3.11/site-packages
/usr/lib/python3.11/site-packages


Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-woc in /home/cdamron3/.local/lib/python3.11/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/cdamron3/.local/lib/python3.11/site-packages (3.0.6)
Requirement already satisfied: matplotlib in /home/cdamron3/.local/lib/python3.11/site-packages (3.11.2)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-woc) (4.70.0)
Requirement already satisfied: anyio in /home/cdamron3/.local/lib/python3.11/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.14.2)
Requirement already satisfied: certifi in /home/cdamron3/.local/lib/python3.11/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/cdamron3/.local/lib/python3.11/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /home/cdamron3/.local/lib/python3.11/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.19)
Requirement already satisfied: h11>=0.16 in /home/cdamron3/.local/lib/python3.11/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: numpy>=1.26.0 in /home/cdamron3/.local/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/cdamron3/.local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/cdamron3/.local/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/cdamron3/.local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: typing_extensions>=4.5 in /home/cdamron3/.local/lib/python3.11/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.16.0)

In [16]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
    'MariaNattestad/Ribbon',
    'stan-dev/cmdstanpy',
    'rveltz/PiecewiseDeterministicMarkovProcesses.jl',
    'lpwgroup/crank',
    'thelfer/MFrontGenericInterfaceSupport',
    'jonescompneurolab/hnn',
    'mirnylab/cooler',
    'jhuapl-boss/intern',
    'privefl/bigstatsr',
    'xeokit/xeokit-sdk'
]

list_df_commits = []

for prj in projects:
    # Convert GitHub repository names to WoC V2412 project names
    woc_prj = prj.lower().replace('/','_',2)

    print(f"Getting commits for {woc_prj}...")

    try:
        commits = woc.get_values('p2c', woc_prj)
        df = pd.DataFrame(commits, columns=["sha1"])
        df['project'] = woc_prj
        list_df_commits.append(df)

        print(f"  Found {len(df)} commits")
    except KeyError as e:
        print(f"  ERROR retrieving {woc_prj}: {e}")
        

df = pd.concat(list_df_commits, ignore_index = True)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv', index = False)
df.head(1)

Getting commits for marianattestad_ribbon...
  Found 519 commits
Getting commits for stan-dev_cmdstanpy...
  Found 2742 commits
Getting commits for rveltz_piecewisedeterministicmarkovprocesses.jl...
  Found 608 commits
Getting commits for lpwgroup_crank...
  Found 370 commits
Getting commits for thelfer_mfrontgenericinterfacesupport...
  Found 753 commits
Getting commits for jonescompneurolab_hnn...
  Found 2050 commits
Getting commits for mirnylab_cooler...
  Found 1406 commits
Getting commits for jhuapl-boss_intern...
  Found 1475 commits
Getting commits for privefl_bigstatsr...
  Found 1007 commits
Getting commits for xeokit_xeokit-sdk...
  Found 15141 commits

                                       sha1                project
0  0023779e992f3962eecf62e652ba81fe66da3852  marianattestad_ribbon

In [17]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
from tqdm import tqdm

# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())
  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch', chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

 17%|█████████████▌                                                                 | 446/2608 [07:43<38:02,  1.06s/it]

Got Errors {'3e201a4346497f954f6feb069ce688c6e6bd299e': 'Key 3e201a4346497f954f6feb069ce688c6e6bd299e not found in /da5_fast/All.sha1c/commit_62.tch'}

 17%|█████████████▊                                                                 | 456/2608 [07:54<37:31,  1.05s/it]

Got Errors {'5fda28b204b7644c981ba18ca3cfedf55667b709': 'Key 5fda28b204b7644c981ba18ca3cfedf55667b709 not found in /da5_fast/All.sha1c/commit_95.tch'}

 20%|███████████████▌                                                               | 513/2608 [08:53<36:21,  1.04s/it]

Got Errors {'10fb011dbb1578bc1dc60c23120d2583baf97e12': 'Key 10fb011dbb1578bc1dc60c23120d2583baf97e12 not found in /da5_fast/All.sha1c/commit_16.tch'}

 28%|██████████████████████                                                         | 730/2608 [12:39<32:30,  1.04s/it]

Got Errors {'2df19d1732de34e3cee4e683f4302bf49c12a3bc': 'Key 2df19d1732de34e3cee4e683f4302bf49c12a3bc not found in /da5_fast/All.sha1c/commit_45.tch'}

 28%|██████████████████████▍                                                        | 742/2608 [12:51<32:26,  1.04s/it]

Got Errors {'41f29c77ee591710a1939217fa6441eafb9e82c6': 'Key 41f29c77ee591710a1939217fa6441eafb9e82c6 not found in /da5_fast/All.sha1c/commit_65.tch'}

 32%|████████████████████████▉                                                      | 824/2608 [14:17<30:50,  1.04s/it]

Got Errors {'d613ae2b60aa023c81c6f6c188bb6305be23680b': 'Key d613ae2b60aa023c81c6f6c188bb6305be23680b not found in /da5_fast/All.sha1c/commit_86.tch'}

 34%|██████████████████████████▊                                                    | 885/2608 [15:20<29:47,  1.04s/it]

Got Errors {'447acf6dbdfc2729d044544622e4fb450d4956ee': 'Key 447acf6dbdfc2729d044544622e4fb450d4956ee not found in /da5_fast/All.sha1c/commit_68.tch'}

 35%|███████████████████████████▊                                                   | 917/2608 [15:53<29:27,  1.05s/it]

Got Errors {'773a5de2d759fe943ac3b3cbdbc43419d2148058': 'Key 773a5de2d759fe943ac3b3cbdbc43419d2148058 not found in /da5_fast/All.sha1c/commit_119.tch'}

 36%|████████████████████████████                                                   | 928/2608 [16:05<29:05,  1.04s/it]

Got Errors {'8e13df89ae0b2d2d94223acad1ad367944fcb82d': 'Key 8e13df89ae0b2d2d94223acad1ad367944fcb82d not found in /da5_fast/All.sha1c/commit_14.tch'}

 37%|█████████████████████████████▍                                                 | 971/2608 [16:49<28:12,  1.03s/it]

Got Errors {'dc39df8ef7ed9d830d67cebf9b49cfab977c18f3': 'Key dc39df8ef7ed9d830d67cebf9b49cfab977c18f3 not found in /da5_fast/All.sha1c/commit_92.tch'}

 42%|████████████████████████████████▊                                             | 1097/2608 [19:00<26:09,  1.04s/it]

Got Errors {'008be06c08d8aa7d56f0056b8e864e1523967b37': 'Key 008be06c08d8aa7d56f0056b8e864e1523967b37 not found in /da5_fast/All.sha1c/commit_0.tch'}

 43%|█████████████████████████████████▌                                            | 1123/2608 [19:27<25:40,  1.04s/it]

Got Errors {'04beebb6bc2ab830039ad23e343432aae980ecf7': 'Key 04beebb6bc2ab830039ad23e343432aae980ecf7 not found in /da5_fast/All.sha1c/commit_4.tch'}

 44%|██████████████████████████████████▏                                           | 1142/2608 [19:46<25:21,  1.04s/it]

Got Errors {'07e968a373c40cdb25b99876ee7391f7b636f17a': 'Key 07e968a373c40cdb25b99876ee7391f7b636f17a not found in /da5_fast/All.sha1c/commit_7.tch'}

 44%|██████████████████████████████████▎                                           | 1147/2608 [19:52<25:16,  1.04s/it]

Got Errors {'08b8adcf47b435482f543f4d38bb07767402af2d': 'Key 08b8adcf47b435482f543f4d38bb07767402af2d not found in /da5_fast/All.sha1c/commit_8.tch'}

 44%|██████████████████████████████████▎                                           | 1148/2608 [19:53<25:13,  1.04s/it]

Got Errors {'08d4c463ce7c46a1278b3340b0af7a4c878b6060': 'Key 08d4c463ce7c46a1278b3340b0af7a4c878b6060 not found in /da5_fast/All.sha1c/commit_8.tch', '08ee86b447ac060bb83453c370c4758cca67573f': 'Key 08ee86b447ac060bb83453c370c4758cca67573f not found in /da5_fast/All.sha1c/commit_8.tch'}

 44%|██████████████████████████████████▌                                           | 1156/2608 [20:01<25:10,  1.04s/it]

Got Errors {'0a48d9c35744afe736b82d93529d5f5dbfe4fe2d': 'Key 0a48d9c35744afe736b82d93529d5f5dbfe4fe2d not found in /da5_fast/All.sha1c/commit_10.tch'}

 45%|██████████████████████████████████▊                                           | 1164/2608 [20:09<25:01,  1.04s/it]

Got Errors {'0b2fa5a98fb7b3787bb7fc29d822bfccf2418892': 'Key 0b2fa5a98fb7b3787bb7fc29d822bfccf2418892 not found in /da5_fast/All.sha1c/commit_11.tch'}

 45%|██████████████████████████████████▉                                           | 1168/2608 [20:13<24:56,  1.04s/it]

Got Errors {'0bba899723988161e194162439f4e529fbe84c4e': 'Key 0bba899723988161e194162439f4e529fbe84c4e not found in /da5_fast/All.sha1c/commit_11.tch'}

 45%|███████████████████████████████████                                           | 1173/2608 [20:19<24:50,  1.04s/it]

Got Errors {'0ca0bad9250407f6e55da73eaaf13241b698691c': 'Key 0ca0bad9250407f6e55da73eaaf13241b698691c not found in /da5_fast/All.sha1c/commit_12.tch'}

 45%|███████████████████████████████████▏                                          | 1177/2608 [20:23<24:45,  1.04s/it]

Got Errors {'0d77e60b24efd987a657ab54898792d79575f053': 'Key 0d77e60b24efd987a657ab54898792d79575f053 not found in /da5_fast/All.sha1c/commit_13.tch'}

 45%|███████████████████████████████████▏                                          | 1178/2608 [20:24<24:44,  1.04s/it]

Got Errors {'0d989d3c44ccfe176ece84431a47fa0332883353': 'Key 0d989d3c44ccfe176ece84431a47fa0332883353 not found in /da5_fast/All.sha1c/commit_13.tch', '0db20385daf3089f636b6a833c567fdc948890ca': 'Key 0db20385daf3089f636b6a833c567fdc948890ca not found in /da5_fast/All.sha1c/commit_13.tch'}

 46%|███████████████████████████████████▋                                          | 1193/2608 [20:39<24:28,  1.04s/it]

Got Errors {'107ab6c4604cec54ddd4697a9a87b1207981ca5e': 'Key 107ab6c4604cec54ddd4697a9a87b1207981ca5e not found in /da5_fast/All.sha1c/commit_16.tch'}

 46%|████████████████████████████████████▏                                         | 1211/2608 [20:58<24:14,  1.04s/it]

Got Errors {'1361164bde56a1a131c9936062c578d93e270ec7': 'Key 1361164bde56a1a131c9936062c578d93e270ec7 not found in /da5_fast/All.sha1c/commit_19.tch'}

 47%|████████████████████████████████████▌                                         | 1223/2608 [21:11<23:59,  1.04s/it]

Got Errors {'15450109b3f480c9a2e1f5a85663166200bae356': 'Key 15450109b3f480c9a2e1f5a85663166200bae356 not found in /da5_fast/All.sha1c/commit_21.tch'}

 47%|████████████████████████████████████▋                                         | 1228/2608 [21:16<23:54,  1.04s/it]

Got Errors {'1607a9a168000198de64a483391558970cd8645b': 'Key 1607a9a168000198de64a483391558970cd8645b not found in /da5_fast/All.sha1c/commit_22.tch'}

 48%|█████████████████████████████████████                                         | 1240/2608 [21:28<23:43,  1.04s/it]

Got Errors {'180fae37c191047709121b16fe475f5164e9c345': 'Key 180fae37c191047709121b16fe475f5164e9c345 not found in /da5_fast/All.sha1c/commit_24.tch'}

 48%|█████████████████████████████████████▏                                        | 1243/2608 [21:31<23:39,  1.04s/it]

Got Errors {'18a5bbbc70764fbb51cae2ed5654d4f53b91f058': 'Key 18a5bbbc70764fbb51cae2ed5654d4f53b91f058 not found in /da5_fast/All.sha1c/commit_24.tch'}

 48%|█████████████████████████████████████▏                                        | 1244/2608 [21:32<23:37,  1.04s/it]

Got Errors {'18ddbc3a571f620337dfbdc2053704d31ba8659d': 'Key 18ddbc3a571f620337dfbdc2053704d31ba8659d not found in /da5_fast/All.sha1c/commit_24.tch'}

 48%|█████████████████████████████████████▎                                        | 1246/2608 [21:34<23:36,  1.04s/it]

Got Errors {'1914f08a665120141743dea7c97cf2562eb81f88': 'Key 1914f08a665120141743dea7c97cf2562eb81f88 not found in /da5_fast/All.sha1c/commit_25.tch'}

 48%|█████████████████████████████████████▎                                        | 1249/2608 [21:38<23:32,  1.04s/it]

Got Errors {'198ae9cbd40c72fbcea53b2edf08d98c6fdac33e': 'Key 198ae9cbd40c72fbcea53b2edf08d98c6fdac33e not found in /da5_fast/All.sha1c/commit_25.tch'}

 48%|█████████████████████████████████████▍                                        | 1253/2608 [21:42<23:33,  1.04s/it]

Got Errors {'1a7648550aff22a08a3709110db8f551836c1ee4': 'Key 1a7648550aff22a08a3709110db8f551836c1ee4 not found in /da5_fast/All.sha1c/commit_26.tch'}

 48%|█████████████████████████████████████▋                                        | 1262/2608 [21:51<23:19,  1.04s/it]

Got Errors {'1c0cb8ac68843db57905ebd33de90e48ee8b772c': 'Key 1c0cb8ac68843db57905ebd33de90e48ee8b772c not found in /da5_fast/All.sha1c/commit_28.tch'}

 49%|██████████████████████████████████████                                        | 1272/2608 [22:02<23:09,  1.04s/it]

Got Errors {'1db2f986f0881fa41dc87035543fb8e8b105ac88': 'Key 1db2f986f0881fa41dc87035543fb8e8b105ac88 not found in /da5_fast/All.sha1c/commit_29.tch'}

 49%|██████████████████████████████████████                                        | 1274/2608 [22:04<23:33,  1.06s/it]

Got Errors {'1df012c364c6ecf7ef54718b4b8a80605a317fc7': 'Key 1df012c364c6ecf7ef54718b4b8a80605a317fc7 not found in /da5_fast/All.sha1c/commit_29.tch'}

 49%|██████████████████████████████████████▎                                       | 1279/2608 [22:09<23:13,  1.05s/it]

Got Errors {'1eee91dee371000951a9bb2e3458dd05c41322ed': 'Key 1eee91dee371000951a9bb2e3458dd05c41322ed not found in /da5_fast/All.sha1c/commit_30.tch'}

 49%|██████████████████████████████████████▎                                       | 1282/2608 [22:12<23:07,  1.05s/it]

Got Errors {'1f86cd49ece5f93b0851f1b5775d3e0d9361925e': 'Key 1f86cd49ece5f93b0851f1b5775d3e0d9361925e not found in /da5_fast/All.sha1c/commit_31.tch'}

 49%|██████████████████████████████████████▌                                       | 1288/2608 [22:18<22:57,  1.04s/it]

Got Errors {'206c106b4cfe819fc47f4e0d25ee686ec832f6dd': 'Key 206c106b4cfe819fc47f4e0d25ee686ec832f6dd not found in /da5_fast/All.sha1c/commit_32.tch'}

 49%|██████████████████████████████████████▌                                       | 1289/2608 [22:19<22:53,  1.04s/it]

Got Errors {'20a3a6423a19dca97aa7db4342349c99be17d97b': 'Key 20a3a6423a19dca97aa7db4342349c99be17d97b not found in /da5_fast/All.sha1c/commit_32.tch'}

 49%|██████████████████████████████████████▌                                       | 1290/2608 [22:20<22:53,  1.04s/it]

Got Errors {'20c5d5219328db0e2a6ebfd88bbfc44eb0367962': 'Key 20c5d5219328db0e2a6ebfd88bbfc44eb0367962 not found in /da5_fast/All.sha1c/commit_32.tch'}

 50%|██████████████████████████████████████▋                                       | 1292/2608 [22:23<22:54,  1.04s/it]

Got Errors {'210bf695761d29347a0dace778705763ff7f5f4e': 'Key 210bf695761d29347a0dace778705763ff7f5f4e not found in /da5_fast/All.sha1c/commit_33.tch'}

 50%|██████████████████████████████████████▊                                       | 1297/2608 [22:28<22:48,  1.04s/it]

Got Errors {'21e91598237d00cadacc6ede47bd8fdaf6eaceb2': 'Key 21e91598237d00cadacc6ede47bd8fdaf6eaceb2 not found in /da5_fast/All.sha1c/commit_33.tch'}

 50%|███████████████████████████████████████▎                                      | 1314/2608 [22:46<22:35,  1.05s/it]

Got Errors {'251bf50db5d531f33e06f915661131c707602211': 'Key 251bf50db5d531f33e06f915661131c707602211 not found in /da5_fast/All.sha1c/commit_37.tch'}

 51%|███████████████████████████████████████▋                                      | 1325/2608 [22:57<22:20,  1.04s/it]

Got Errors {'26ee8f3d5f31f62e8f33c4dac44337549d603516': 'Key 26ee8f3d5f31f62e8f33c4dac44337549d603516 not found in /da5_fast/All.sha1c/commit_38.tch'}

 51%|███████████████████████████████████████▋                                      | 1329/2608 [23:01<22:22,  1.05s/it]

Got Errors {'27c53c8d61d5a95425295a123b54edc04c974149': 'Key 27c53c8d61d5a95425295a123b54edc04c974149 not found in /da5_fast/All.sha1c/commit_39.tch', '27cc8a544fb266be30d7c5d973301e9b8454827e': 'Key 27cc8a544fb266be30d7c5d973301e9b8454827e not found in /da5_fast/All.sha1c/commit_39.tch'}

 51%|███████████████████████████████████████▊                                      | 1333/2608 [23:05<22:08,  1.04s/it]

Got Errors {'286ab29c5a0508cb79527d195d4c0c774ccb204b': 'Key 286ab29c5a0508cb79527d195d4c0c774ccb204b not found in /da5_fast/All.sha1c/commit_40.tch'}

 51%|███████████████████████████████████████▉                                      | 1336/2608 [23:09<22:08,  1.04s/it]

Got Errors {'28fc07dc98728d145e2d6ebc2f276f8ceec7ec25': 'Key 28fc07dc98728d145e2d6ebc2f276f8ceec7ec25 not found in /da5_fast/All.sha1c/commit_40.tch'}

 51%|████████████████████████████████████████                                      | 1341/2608 [23:14<21:59,  1.04s/it]

Got Errors {'29b7f08416adc17c32c538531bc1ae1952a43114': 'Key 29b7f08416adc17c32c538531bc1ae1952a43114 not found in /da5_fast/All.sha1c/commit_41.tch'}

 51%|████████████████████████████████████████▏                                     | 1342/2608 [23:15<21:59,  1.04s/it]

Got Errors {'29ccdbd1163205715497b1d50088e76e32ffe2c2': 'Key 29ccdbd1163205715497b1d50088e76e32ffe2c2 not found in /da5_fast/All.sha1c/commit_41.tch'}

 52%|████████████████████████████████████████▏                                     | 1345/2608 [23:18<22:04,  1.05s/it]

Got Errors {'2a3fde21c2119d91f3eb9a96825071d3a5e2ca74': 'Key 2a3fde21c2119d91f3eb9a96825071d3a5e2ca74 not found in /da5_fast/All.sha1c/commit_42.tch', '2a4bde6321cf4cc4308d6133aa9649e1aae4e1fa': 'Key 2a4bde6321cf4cc4308d6133aa9649e1aae4e1fa not found in /da5_fast/All.sha1c/commit_42.tch'}

 52%|████████████████████████████████████████▍                                     | 1352/2608 [23:25<21:51,  1.04s/it]

Got Errors {'2b673c7e39f72b7ff1e87c10705959ae0e2a9039': 'Key 2b673c7e39f72b7ff1e87c10705959ae0e2a9039 not found in /da5_fast/All.sha1c/commit_43.tch'}

 52%|████████████████████████████████████████▌                                     | 1358/2608 [23:32<21:44,  1.04s/it]

Got Errors {'2c9906c8544f2a25a0a32663d1c07a8ab8638068': 'Key 2c9906c8544f2a25a0a32663d1c07a8ab8638068 not found in /da5_fast/All.sha1c/commit_44.tch'}

 52%|████████████████████████████████████████▊                                     | 1366/2608 [23:40<21:33,  1.04s/it]

Got Errors {'2e28a3c508fb840ec7a563f1f48fb98bef21eb0c': 'Key 2e28a3c508fb840ec7a563f1f48fb98bef21eb0c not found in /da5_fast/All.sha1c/commit_46.tch'}

 53%|█████████████████████████████████████████                                     | 1373/2608 [23:47<21:35,  1.05s/it]

Got Errors {'2f6ace2a865050252977262a8160db237cef6c2c': 'Key 2f6ace2a865050252977262a8160db237cef6c2c not found in /da5_fast/All.sha1c/commit_47.tch'}

 53%|█████████████████████████████████████████▎                                    | 1380/2608 [23:55<21:18,  1.04s/it]

Got Errors {'30ac0fa9a4eaf6759fe306bb2e332cce49884787': 'Key 30ac0fa9a4eaf6759fe306bb2e332cce49884787 not found in /da5_fast/All.sha1c/commit_48.tch', '30b5d19796d8b480a373f9d2ae75a8218aa88e5a': 'Key 30b5d19796d8b480a373f9d2ae75a8218aa88e5a not found in /da5_fast/All.sha1c/commit_48.tch'}

 53%|█████████████████████████████████████████▎                                    | 1381/2608 [23:56<21:16,  1.04s/it]

Got Errors {'30f9121a8ed802d2af28f241e825a18a49e18039': 'Key 30f9121a8ed802d2af28f241e825a18a49e18039 not found in /da5_fast/All.sha1c/commit_48.tch'}

 54%|██████████████████████████████████████████                                    | 1405/2608 [24:21<20:57,  1.05s/it]

Got Errors {'353ac3c8bff8671d5d46f74e13bd90ab86fa706f': 'Key 353ac3c8bff8671d5d46f74e13bd90ab86fa706f not found in /da5_fast/All.sha1c/commit_53.tch'}

 54%|██████████████████████████████████████████                                    | 1407/2608 [24:23<20:54,  1.04s/it]

Got Errors {'35a140f309c58f7f6e88e722b0c7322a0d05e821': 'Key 35a140f309c58f7f6e88e722b0c7322a0d05e821 not found in /da5_fast/All.sha1c/commit_53.tch'}

 54%|██████████████████████████████████████████                                    | 1408/2608 [24:24<21:02,  1.05s/it]

Got Errors {'35c2cfd18e67d4d890e70b50a163d88ccd6f7081': 'Key 35c2cfd18e67d4d890e70b50a163d88ccd6f7081 not found in /da5_fast/All.sha1c/commit_53.tch'}

 54%|██████████████████████████████████████████▏                                   | 1412/2608 [24:28<20:45,  1.04s/it]

Got Errors {'3671107f6c5d2bc722288a2438a721817fc7eeff': 'Key 3671107f6c5d2bc722288a2438a721817fc7eeff not found in /da5_fast/All.sha1c/commit_54.tch'}

 54%|██████████████████████████████████████████▍                                   | 1419/2608 [24:35<20:36,  1.04s/it]

Got Errors {'3796b67f0bbcca7382160e5030522506fb49a54e': 'Key 3796b67f0bbcca7382160e5030522506fb49a54e not found in /da5_fast/All.sha1c/commit_55.tch'}

 54%|██████████████████████████████████████████▍                                   | 1420/2608 [24:36<20:35,  1.04s/it]

Got Errors {'37b31d85122e7ed94e3bdbb965fe8f02e1dee80b': 'Key 37b31d85122e7ed94e3bdbb965fe8f02e1dee80b not found in /da5_fast/All.sha1c/commit_55.tch', '37cca0a9d4144d4d0a6bd8b69e24bf094e24b113': 'Key 37cca0a9d4144d4d0a6bd8b69e24bf094e24b113 not found in /da5_fast/All.sha1c/commit_55.tch'}

 55%|██████████████████████████████████████████▌                                   | 1424/2608 [24:41<20:42,  1.05s/it]

Got Errors {'38983e0709df66ae5207a744146c48beeaa60f23': 'Key 38983e0709df66ae5207a744146c48beeaa60f23 not found in /da5_fast/All.sha1c/commit_56.tch'}

 55%|██████████████████████████████████████████▋                                   | 1426/2608 [24:43<20:33,  1.04s/it]

Got Errors {'38d236e17a79f8a81adff7dd596bfc083672f408': 'Key 38d236e17a79f8a81adff7dd596bfc083672f408 not found in /da5_fast/All.sha1c/commit_56.tch'}

 55%|██████████████████████████████████████████▋                                   | 1427/2608 [24:44<20:32,  1.04s/it]

Got Errors {'39061799b38a8092a006514d47f8a29ae6d4c0e8': 'Key 39061799b38a8092a006514d47f8a29ae6d4c0e8 not found in /da5_fast/All.sha1c/commit_57.tch'}

 55%|██████████████████████████████████████████▋                                   | 1428/2608 [24:45<20:32,  1.04s/it]

Got Errors {'391b422200d7b5d1990f4b58c506ebde3d01e9cf': 'Key 391b422200d7b5d1990f4b58c506ebde3d01e9cf not found in /da5_fast/All.sha1c/commit_57.tch'}

 56%|███████████████████████████████████████████▊                                  | 1464/2608 [25:22<20:12,  1.06s/it]

Got Errors {'3f92b587f6e55dc27690e22b82595f3cb9b757f6': 'Key 3f92b587f6e55dc27690e22b82595f3cb9b757f6 not found in /da5_fast/All.sha1c/commit_63.tch'}

 56%|███████████████████████████████████████████▊                                  | 1466/2608 [25:25<20:05,  1.06s/it]

Got Errors {'3fe088f9f2eba5733885cb4cfc6fb8490502e399': 'Key 3fe088f9f2eba5733885cb4cfc6fb8490502e399 not found in /da5_fast/All.sha1c/commit_63.tch'}

 56%|███████████████████████████████████████████▉                                  | 1469/2608 [25:28<19:57,  1.05s/it]

Got Errors {'4069e319271a81d738a6d201aa1f9688be202fdf': 'Key 4069e319271a81d738a6d201aa1f9688be202fdf not found in /da5_fast/All.sha1c/commit_64.tch'}

 57%|████████████████████████████████████████████▎                                 | 1481/2608 [25:40<19:32,  1.04s/it]

Got Errors {'42d596ee538ce4f684a39b8e5cbcb1bcd6be82cc': 'Key 42d596ee538ce4f684a39b8e5cbcb1bcd6be82cc not found in /da5_fast/All.sha1c/commit_66.tch'}

 57%|████████████████████████████████████████████▍                                 | 1487/2608 [25:47<19:36,  1.05s/it]

Got Errors {'4381e1d7271b3d81bddd3dd026267bb20ecd2337': 'Key 4381e1d7271b3d81bddd3dd026267bb20ecd2337 not found in /da5_fast/All.sha1c/commit_67.tch'}

 57%|████████████████████████████████████████████▌                                 | 1489/2608 [25:49<19:32,  1.05s/it]

Got Errors {'440e68f5300df24e6bb586389dd6d799dbc6bab7': 'Key 440e68f5300df24e6bb586389dd6d799dbc6bab7 not found in /da5_fast/All.sha1c/commit_68.tch'}

 57%|████████████████████████████████████████████▌                                 | 1492/2608 [25:52<19:22,  1.04s/it]

Got Errors {'44840403327321e64f3ad12c5de2fddc8e5753b0': 'Key 44840403327321e64f3ad12c5de2fddc8e5753b0 not found in /da5_fast/All.sha1c/commit_68.tch'}

 57%|████████████████████████████████████████████▊                                 | 1498/2608 [25:58<19:16,  1.04s/it]

Got Errors {'45633bdb59bf5ccc2d2a7a370c33886145edacdf': 'Key 45633bdb59bf5ccc2d2a7a370c33886145edacdf not found in /da5_fast/All.sha1c/commit_69.tch', '4568c29667d88e1ae49b8a20ca1e8b468263b74f': 'Key 4568c29667d88e1ae49b8a20ca1e8b468263b74f not found in /da5_fast/All.sha1c/commit_69.tch'}

 57%|████████████████████████████████████████████▊                                 | 1499/2608 [25:59<19:16,  1.04s/it]

Got Errors {'459ac31caa7abb107ebebba6d6e3f5460662f6c4': 'Key 459ac31caa7abb107ebebba6d6e3f5460662f6c4 not found in /da5_fast/All.sha1c/commit_69.tch'}

 58%|████████████████████████████████████████████▉                                 | 1504/2608 [26:04<19:28,  1.06s/it]

Got Errors {'463a3dbabc3744403f57900a24c3eb524a2be87c': 'Key 463a3dbabc3744403f57900a24c3eb524a2be87c not found in /da5_fast/All.sha1c/commit_70.tch'}

 58%|█████████████████████████████████████████████                                 | 1508/2608 [26:08<19:06,  1.04s/it]

Got Errors {'47044ad1f1cb51f8909e18458a775b2eeba51ebd': 'Key 47044ad1f1cb51f8909e18458a775b2eeba51ebd not found in /da5_fast/All.sha1c/commit_71.tch'}

 58%|█████████████████████████████████████████████▏                                | 1512/2608 [26:13<19:06,  1.05s/it]

Got Errors {'479dcee6047dde8746955a6dcfa6461611dcee15': 'Key 479dcee6047dde8746955a6dcfa6461611dcee15 not found in /da5_fast/All.sha1c/commit_71.tch', '47a874806d96ff09df79b3f4d2b28f6d3d8ce71f': 'Key 47a874806d96ff09df79b3f4d2b28f6d3d8ce71f not found in /da5_fast/All.sha1c/commit_71.tch'}

 58%|█████████████████████████████████████████████▎                                | 1513/2608 [26:14<19:03,  1.04s/it]

Got Errors {'47d3e6ec95ffe459a5177d0b564389a7d9c9383e': 'Key 47d3e6ec95ffe459a5177d0b564389a7d9c9383e not found in /da5_fast/All.sha1c/commit_71.tch'}

 58%|█████████████████████████████████████████████▎                                | 1514/2608 [26:15<19:03,  1.05s/it]

Got Errors {'47fba37d2065a746a915c8aac33646b757c91b26': 'Key 47fba37d2065a746a915c8aac33646b757c91b26 not found in /da5_fast/All.sha1c/commit_71.tch'}

 58%|█████████████████████████████████████████████▍                                | 1519/2608 [26:20<19:16,  1.06s/it]

Got Errors {'48f9883b8fe69f7eeef0197159f278a62549e59f': 'Key 48f9883b8fe69f7eeef0197159f278a62549e59f not found in /da5_fast/All.sha1c/commit_72.tch'}

 58%|█████████████████████████████████████████████▌                                | 1522/2608 [26:23<19:09,  1.06s/it]

Got Errors {'499f4c1019c26cc4e414beb56c244715f307f6bd': 'Key 499f4c1019c26cc4e414beb56c244715f307f6bd not found in /da5_fast/All.sha1c/commit_73.tch'}

 59%|█████████████████████████████████████████████▋                                | 1526/2608 [26:27<18:48,  1.04s/it]

Got Errors {'4a1b4db384c23fb730639f26d01693d3485afcf6': 'Key 4a1b4db384c23fb730639f26d01693d3485afcf6 not found in /da5_fast/All.sha1c/commit_74.tch'}

 59%|█████████████████████████████████████████████▋                                | 1529/2608 [26:31<18:46,  1.04s/it]

Got Errors {'4aa998e3fab4b0637e2fdabb5582f0d4c7f67d18': 'Key 4aa998e3fab4b0637e2fdabb5582f0d4c7f67d18 not found in /da5_fast/All.sha1c/commit_74.tch'}

 59%|█████████████████████████████████████████████▊                                | 1531/2608 [26:33<18:41,  1.04s/it]

Got Errors {'4b03a0e420b8ead0f2ca192d3419f5e885491f82': 'Key 4b03a0e420b8ead0f2ca192d3419f5e885491f82 not found in /da5_fast/All.sha1c/commit_75.tch'}

 59%|█████████████████████████████████████████████▊                                | 1533/2608 [26:35<18:42,  1.04s/it]

Got Errors {'4b3f359786dee2f44ae23571b66d355f92e3513a': 'Key 4b3f359786dee2f44ae23571b66d355f92e3513a not found in /da5_fast/All.sha1c/commit_75.tch'}

 59%|██████████████████████████████████████████████▍                               | 1551/2608 [26:54<18:30,  1.05s/it]

Got Errors {'4e5a8e23850afe3e7b46ca678aefb93538107011': 'Key 4e5a8e23850afe3e7b46ca678aefb93538107011 not found in /da5_fast/All.sha1c/commit_78.tch'}

 60%|██████████████████████████████████████████████▌                               | 1555/2608 [26:58<18:26,  1.05s/it]

Got Errors {'4f1731ee54cf04bb93b9f3b189f581149041db48': 'Key 4f1731ee54cf04bb93b9f3b189f581149041db48 not found in /da5_fast/All.sha1c/commit_79.tch'}

 60%|██████████████████████████████████████████████▌                               | 1556/2608 [26:59<18:21,  1.05s/it]

Got Errors {'4f3eff16a2d5252348476c76a017a55b6a25b07b': 'Key 4f3eff16a2d5252348476c76a017a55b6a25b07b not found in /da5_fast/All.sha1c/commit_79.tch'}

 60%|██████████████████████████████████████████████▌                               | 1558/2608 [27:01<18:14,  1.04s/it]

Got Errors {'4faa48bc2ffab221b15103ab8cd1c251080decbd': 'Key 4faa48bc2ffab221b15103ab8cd1c251080decbd not found in /da5_fast/All.sha1c/commit_79.tch'}

 60%|██████████████████████████████████████████████▊                               | 1564/2608 [27:07<18:17,  1.05s/it]

Got Errors {'50d1c8365e5df49fbed606343fe213de3a433ee6': 'Key 50d1c8365e5df49fbed606343fe213de3a433ee6 not found in /da5_fast/All.sha1c/commit_80.tch', '50d8b67671d163b9d3520c5dfa15b769ef156511': 'Key 50d8b67671d163b9d3520c5dfa15b769ef156511 not found in /da5_fast/All.sha1c/commit_80.tch'}

 60%|██████████████████████████████████████████████▉                               | 1570/2608 [27:14<18:27,  1.07s/it]

Got Errors {'522e42cff327b4f9ecd541735f6e82cce9e4f814': 'Key 522e42cff327b4f9ecd541735f6e82cce9e4f814 not found in /da5_fast/All.sha1c/commit_82.tch'}

 61%|███████████████████████████████████████████████▎                              | 1581/2608 [27:25<17:51,  1.04s/it]

Got Errors {'53ce4ad9f5896b5e2bdc3fed38b6520ef4dd8733': 'Key 53ce4ad9f5896b5e2bdc3fed38b6520ef4dd8733 not found in /da5_fast/All.sha1c/commit_83.tch'}

 61%|███████████████████████████████████████████████▌                              | 1591/2608 [27:36<17:40,  1.04s/it]

Got Errors {'554dd762cf020eed2608925c75411da16a6eedc9': 'Key 554dd762cf020eed2608925c75411da16a6eedc9 not found in /da5_fast/All.sha1c/commit_85.tch'}

 61%|███████████████████████████████████████████████▊                              | 1597/2608 [27:42<17:36,  1.05s/it]

Got Errors {'563f651c427f4c7628b6a2142935589427c374da': 'Key 563f651c427f4c7628b6a2142935589427c374da not found in /da5_fast/All.sha1c/commit_86.tch'}

 61%|███████████████████████████████████████████████▉                              | 1603/2608 [27:48<17:33,  1.05s/it]

Got Errors {'57573716b0bf7d86d981b3d55416da9468c884e6': 'Key 57573716b0bf7d86d981b3d55416da9468c884e6 not found in /da5_fast/All.sha1c/commit_87.tch'}

 62%|████████████████████████████████████████████████▏                             | 1611/2608 [27:56<17:25,  1.05s/it]

Got Errors {'58e30cad69acfc90a2dd0dd8d2e953e0d471a893': 'Key 58e30cad69acfc90a2dd0dd8d2e953e0d471a893 not found in /da5_fast/All.sha1c/commit_88.tch'}

 62%|████████████████████████████████████████████████▏                             | 1613/2608 [27:59<17:23,  1.05s/it]

Got Errors {'594248ac68ae11b68a36bda13b130d2ec96d549c': 'Key 594248ac68ae11b68a36bda13b130d2ec96d549c not found in /da5_fast/All.sha1c/commit_89.tch'}

 62%|████████████████████████████████████████████████▋                             | 1627/2608 [28:13<17:10,  1.05s/it]

Got Errors {'5bbb540d5842364aa3d77cdd333100597a511299': 'Key 5bbb540d5842364aa3d77cdd333100597a511299 not found in /da5_fast/All.sha1c/commit_91.tch'}

 62%|████████████████████████████████████████████████▊                             | 1630/2608 [28:16<17:09,  1.05s/it]

Got Errors {'5c04a3a4c08bf73e68f8869b442dcb03cf9628c7': 'Key 5c04a3a4c08bf73e68f8869b442dcb03cf9628c7 not found in /da5_fast/All.sha1c/commit_92.tch'}

 63%|████████████████████████████████████████████████▉                             | 1638/2608 [28:25<16:56,  1.05s/it]

Got Errors {'5d3f0aa039e230b16b6b1709155c42f4eb0db544': 'Key 5d3f0aa039e230b16b6b1709155c42f4eb0db544 not found in /da5_fast/All.sha1c/commit_93.tch', '5d5b0f525428547991cf041e4876121c56839285': 'Key 5d5b0f525428547991cf041e4876121c56839285 not found in /da5_fast/All.sha1c/commit_93.tch'}

 63%|█████████████████████████████████████████████████▏                            | 1645/2608 [28:32<16:50,  1.05s/it]

Got Errors {'5e6195dd3d7df276fd675f1963e6bd244ad2839a': 'Key 5e6195dd3d7df276fd675f1963e6bd244ad2839a not found in /da5_fast/All.sha1c/commit_94.tch'}

 63%|█████████████████████████████████████████████████▎                            | 1647/2608 [28:34<16:46,  1.05s/it]

Got Errors {'5ecf8c417b793edcb909c3172f3a027cc76e38ba': 'Key 5ecf8c417b793edcb909c3172f3a027cc76e38ba not found in /da5_fast/All.sha1c/commit_94.tch'}

 63%|█████████████████████████████████████████████████▎                            | 1649/2608 [28:36<16:48,  1.05s/it]

Got Errors {'5f1c7b4f4e77b6e8bb87cf073c4b04d095463bbe': 'Key 5f1c7b4f4e77b6e8bb87cf073c4b04d095463bbe not found in /da5_fast/All.sha1c/commit_95.tch', '5f2797e58c0c8a5b39b59ad7762eb484e8019ad7': 'Key 5f2797e58c0c8a5b39b59ad7762eb484e8019ad7 not found in /da5_fast/All.sha1c/commit_95.tch'}

 63%|█████████████████████████████████████████████████▍                            | 1651/2608 [28:38<16:44,  1.05s/it]

Got Errors {'5f705e62e43344a9032df1d1f35a99354ad520be': 'Key 5f705e62e43344a9032df1d1f35a99354ad520be not found in /da5_fast/All.sha1c/commit_95.tch'}

 63%|█████████████████████████████████████████████████▌                            | 1656/2608 [28:44<16:30,  1.04s/it]

Got Errors {'604555c6bbae1bf7838775e1d607c13350bc15d2': 'Key 604555c6bbae1bf7838775e1d607c13350bc15d2 not found in /da5_fast/All.sha1c/commit_96.tch', '604ac0bef067d6b71d61c48e5467ec9ddaaba4bc': 'Key 604ac0bef067d6b71d61c48e5467ec9ddaaba4bc not found in /da5_fast/All.sha1c/commit_96.tch', '605ce4f75302aabe98950597e2511c81ca762465': 'Key 605ce4f75302aabe98950597e2511c81ca762465 not found in /da5_fast/All.sha1c/commit_96.tch'}

 64%|█████████████████████████████████████████████████▌                            | 1659/2608 [28:47<16:33,  1.05s/it]

Got Errors {'60d5802f8c78771b64247c5a09e56b606bd87a04': 'Key 60d5802f8c78771b64247c5a09e56b606bd87a04 not found in /da5_fast/All.sha1c/commit_96.tch'}

 64%|█████████████████████████████████████████████████▋                            | 1660/2608 [28:48<16:31,  1.05s/it]

Got Errors {'60e2db23d9fa207d143e838ed4766605938fe99b': 'Key 60e2db23d9fa207d143e838ed4766605938fe99b not found in /da5_fast/All.sha1c/commit_96.tch'}

 64%|█████████████████████████████████████████████████▊                            | 1665/2608 [28:53<16:27,  1.05s/it]

Got Errors {'61acecacde942a882c375c80afeebc4c3ae803a3': 'Key 61acecacde942a882c375c80afeebc4c3ae803a3 not found in /da5_fast/All.sha1c/commit_97.tch', '61d35f92cf5667c5f242b3777480f104791188c2': 'Key 61d35f92cf5667c5f242b3777480f104791188c2 not found in /da5_fast/All.sha1c/commit_97.tch'}

 64%|██████████████████████████████████████████████████▏                           | 1680/2608 [29:09<16:17,  1.05s/it]

Got Errors {'649a072eb207304f754acd57ae94d430408ac1cb': 'Key 649a072eb207304f754acd57ae94d430408ac1cb not found in /da5_fast/All.sha1c/commit_100.tch'}

 65%|██████████████████████████████████████████████████▋                           | 1693/2608 [29:22<15:58,  1.05s/it]

Got Errors {'66bfa2391d86b9357ae3d5864806f2b27c689ad4': 'Key 66bfa2391d86b9357ae3d5864806f2b27c689ad4 not found in /da5_fast/All.sha1c/commit_102.tch'}

 65%|██████████████████████████████████████████████████▋                           | 1694/2608 [29:24<15:54,  1.04s/it]

Got Errors {'66c961aa9fb128cbd737808b79583eafcf744479': 'Key 66c961aa9fb128cbd737808b79583eafcf744479 not found in /da5_fast/All.sha1c/commit_102.tch'}

 65%|██████████████████████████████████████████████████▋                           | 1695/2608 [29:25<15:53,  1.04s/it]

Got Errors {'66ebaf7d6cb5c5a66e1e1b2809cb459db5efc623': 'Key 66ebaf7d6cb5c5a66e1e1b2809cb459db5efc623 not found in /da5_fast/All.sha1c/commit_102.tch', '66ecd21d62e5efabb71d4f9acccde0dc0f93e79f': 'Key 66ecd21d62e5efabb71d4f9acccde0dc0f93e79f not found in /da5_fast/All.sha1c/commit_102.tch'}

 65%|██████████████████████████████████████████████████▋                           | 1696/2608 [29:26<15:56,  1.05s/it]

Got Errors {'672b3123a2d20cd69e46a2561ce171aee4ad2fe6': 'Key 672b3123a2d20cd69e46a2561ce171aee4ad2fe6 not found in /da5_fast/All.sha1c/commit_103.tch'}

 66%|███████████████████████████████████████████████████▏                          | 1713/2608 [29:43<15:40,  1.05s/it]

Got Errors {'6a62dae4aeffd6e908c1e965228ecdaa4cc3369a': 'Key 6a62dae4aeffd6e908c1e965228ecdaa4cc3369a not found in /da5_fast/All.sha1c/commit_106.tch'}

 66%|███████████████████████████████████████████████████▎                          | 1717/2608 [29:48<15:29,  1.04s/it]

Got Errors {'6af674fd94d2dfc4ba4271352324273ddbafb9a0': 'Key 6af674fd94d2dfc4ba4271352324273ddbafb9a0 not found in /da5_fast/All.sha1c/commit_106.tch'}

 66%|███████████████████████████████████████████████████▍                          | 1720/2608 [29:51<15:26,  1.04s/it]

Got Errors {'6b52f9c2766ee7fbb614e2079d9ef51cc0051fe5': 'Key 6b52f9c2766ee7fbb614e2079d9ef51cc0051fe5 not found in /da5_fast/All.sha1c/commit_107.tch'}

 66%|███████████████████████████████████████████████████▌                          | 1723/2608 [29:54<15:22,  1.04s/it]

Got Errors {'6bda80f9b1b96a8e11269514104d87dd67d18cb7': 'Key 6bda80f9b1b96a8e11269514104d87dd67d18cb7 not found in /da5_fast/All.sha1c/commit_107.tch'}

 66%|███████████████████████████████████████████████████▋                          | 1728/2608 [29:59<15:17,  1.04s/it]

Got Errors {'6cbb98ed49068c49a5e60cf80597eebeea03494a': 'Key 6cbb98ed49068c49a5e60cf80597eebeea03494a not found in /da5_fast/All.sha1c/commit_108.tch'}

 67%|████████████████████████████████████████████████████▎                         | 1749/2608 [30:21<15:01,  1.05s/it]

Got Errors {'7018955b33cfa0e85bad47cfe0cb335dab868074': 'Key 7018955b33cfa0e85bad47cfe0cb335dab868074 not found in /da5_fast/All.sha1c/commit_112.tch'}

 67%|████████████████████████████████████████████████████▎                         | 1750/2608 [30:22<14:58,  1.05s/it]

Got Errors {'70421654d49e1adaa86eb6b55e3af01a84addb82': 'Key 70421654d49e1adaa86eb6b55e3af01a84addb82 not found in /da5_fast/All.sha1c/commit_112.tch'}

 67%|████████████████████████████████████████████████████▍                         | 1753/2608 [30:25<14:52,  1.04s/it]

Got Errors {'709dbb3fb2032c8aadaba9b9ba8d9084662cabed': 'Key 709dbb3fb2032c8aadaba9b9ba8d9084662cabed not found in /da5_fast/All.sha1c/commit_112.tch'}

 67%|████████████████████████████████████████████████████▍                         | 1754/2608 [30:26<14:52,  1.04s/it]

Got Errors {'70c7e02ac82252ac2e4085275c45e9c9a196d8c1': 'Key 70c7e02ac82252ac2e4085275c45e9c9a196d8c1 not found in /da5_fast/All.sha1c/commit_112.tch'}

 68%|████████████████████████████████████████████████████▊                         | 1765/2608 [30:38<14:41,  1.05s/it]

Got Errors {'72ba79a489509f5811ef85d079b7e0988fab6ef5': 'Key 72ba79a489509f5811ef85d079b7e0988fab6ef5 not found in /da5_fast/All.sha1c/commit_114.tch'}

 68%|████████████████████████████████████████████████████▊                         | 1767/2608 [30:40<14:36,  1.04s/it]

Got Errors {'73172cc393ad1a3a09cd710025cb38ae98c4f269': 'Key 73172cc393ad1a3a09cd710025cb38ae98c4f269 not found in /da5_fast/All.sha1c/commit_115.tch', '732a539ef55a6569e806257b71dcf83a24e6aa0b': 'Key 732a539ef55a6569e806257b71dcf83a24e6aa0b not found in /da5_fast/All.sha1c/commit_115.tch'}

 68%|████████████████████████████████████████████████████▉                         | 1768/2608 [30:41<14:33,  1.04s/it]

Got Errors {'73562293c8549e129614d7fdcb265676ec3d60e0': 'Key 73562293c8549e129614d7fdcb265676ec3d60e0 not found in /da5_fast/All.sha1c/commit_115.tch'}

 68%|████████████████████████████████████████████████████▉                         | 1772/2608 [30:45<14:33,  1.04s/it]

Got Errors {'73e0fd2a3b48e0cfb27340d6547bd2926ab735ec': 'Key 73e0fd2a3b48e0cfb27340d6547bd2926ab735ec not found in /da5_fast/All.sha1c/commit_115.tch'}

 68%|█████████████████████████████████████████████████████                         | 1773/2608 [30:46<14:33,  1.05s/it]

Got Errors {'740a08bb62b1f2d9de85134b9a8e7aed4bf84b93': 'Key 740a08bb62b1f2d9de85134b9a8e7aed4bf84b93 not found in /da5_fast/All.sha1c/commit_116.tch'}

 68%|█████████████████████████████████████████████████████▏                        | 1779/2608 [30:53<14:30,  1.05s/it]

Got Errors {'74ffae3b3bc1b36b0937060f9248e52f2260975d': 'Key 74ffae3b3bc1b36b0937060f9248e52f2260975d not found in /da5_fast/All.sha1c/commit_116.tch'}

 68%|█████████████████████████████████████████████████████▎                        | 1781/2608 [30:55<14:31,  1.05s/it]

Got Errors {'7565d7d114f5a833b61ba5c74f4e66833e2812f9': 'Key 7565d7d114f5a833b61ba5c74f4e66833e2812f9 not found in /da5_fast/All.sha1c/commit_117.tch'}

 68%|█████████████████████████████████████████████████████▎                        | 1784/2608 [30:58<14:20,  1.04s/it]

Got Errors {'75ccefc64177967ead619cc5f305a3a5872b70a8': 'Key 75ccefc64177967ead619cc5f305a3a5872b70a8 not found in /da5_fast/All.sha1c/commit_117.tch'}

 68%|█████████████████████████████████████████████████████▍                        | 1786/2608 [31:00<14:19,  1.05s/it]

Got Errors {'761bc520558f8d13871b42e205bea4d970e4b931': 'Key 761bc520558f8d13871b42e205bea4d970e4b931 not found in /da5_fast/All.sha1c/commit_118.tch'}

 69%|█████████████████████████████████████████████████████▍                        | 1787/2608 [31:01<14:18,  1.05s/it]

Got Errors {'763ac72f7ea45c593d7d8061f2fa325ac93b4f35': 'Key 763ac72f7ea45c593d7d8061f2fa325ac93b4f35 not found in /da5_fast/All.sha1c/commit_118.tch'}

 69%|█████████████████████████████████████████████████████▌                        | 1790/2608 [31:04<14:12,  1.04s/it]

Got Errors {'76b3bf4a98c328e4889bcb1ca97688a85437c029': 'Key 76b3bf4a98c328e4889bcb1ca97688a85437c029 not found in /da5_fast/All.sha1c/commit_118.tch'}

 69%|█████████████████████████████████████████████████████▋                        | 1794/2608 [31:08<14:14,  1.05s/it]

Got Errors {'7786e3eb916caeafa35df8adf0634228b15bcaa8': 'Key 7786e3eb916caeafa35df8adf0634228b15bcaa8 not found in /da5_fast/All.sha1c/commit_119.tch'}

 69%|█████████████████████████████████████████████████████▋                        | 1795/2608 [31:09<14:11,  1.05s/it]

Got Errors {'77b1ecad32bc04214ed754fbdeaa58957ab73bec': 'Key 77b1ecad32bc04214ed754fbdeaa58957ab73bec not found in /da5_fast/All.sha1c/commit_119.tch', '77b21b1756bad3c7fd94faa7388467c3bc423fae': 'Key 77b21b1756bad3c7fd94faa7388467c3bc423fae not found in /da5_fast/All.sha1c/commit_119.tch'}

 69%|█████████████████████████████████████████████████████▊                        | 1798/2608 [31:12<14:03,  1.04s/it]

Got Errors {'784c673a67a82bbba3281e38e2e40d26132c4840': 'Key 784c673a67a82bbba3281e38e2e40d26132c4840 not found in /da5_fast/All.sha1c/commit_120.tch'}

 69%|█████████████████████████████████████████████████████▉                        | 1803/2608 [31:18<14:04,  1.05s/it]

Got Errors {'794d7699294382c042a49d13fd291eaf80ec2ea4': 'Key 794d7699294382c042a49d13fd291eaf80ec2ea4 not found in /da5_fast/All.sha1c/commit_121.tch'}

 69%|██████████████████████████████████████████████████████                        | 1809/2608 [31:24<14:01,  1.05s/it]

Got Errors {'7a4d724a55a508d0bb365f751ff9e10dddfe9af8': 'Key 7a4d724a55a508d0bb365f751ff9e10dddfe9af8 not found in /da5_fast/All.sha1c/commit_122.tch'}

 69%|██████████████████████████████████████████████████████▏                       | 1812/2608 [31:27<13:51,  1.04s/it]

Got Errors {'7af9e18423383276365777967536912109885b0b': 'Key 7af9e18423383276365777967536912109885b0b not found in /da5_fast/All.sha1c/commit_122.tch'}

 70%|██████████████████████████████████████████████████████▏                       | 1813/2608 [31:28<13:51,  1.05s/it]

Got Errors {'7b190d65b58b047e39ab26b87aba746b89562e8e': 'Key 7b190d65b58b047e39ab26b87aba746b89562e8e not found in /da5_fast/All.sha1c/commit_123.tch'}

 70%|██████████████████████████████████████████████████████▍                       | 1819/2608 [31:35<14:21,  1.09s/it]

Got Errors {'7c124066354db24c4aa01a90fd6c3be8b2a31279': 'Key 7c124066354db24c4aa01a90fd6c3be8b2a31279 not found in /da5_fast/All.sha1c/commit_124.tch'}

 70%|██████████████████████████████████████████████████████▉                       | 1837/2608 [31:53<13:27,  1.05s/it]

Got Errors {'7f51964e7468bd6e21ba922c7df459616b9a52f3': 'Key 7f51964e7468bd6e21ba922c7df459616b9a52f3 not found in /da5_fast/All.sha1c/commit_127.tch', '7f7b150481fa79e3e669767db64fd9637a51b3c9': 'Key 7f7b150481fa79e3e669767db64fd9637a51b3c9 not found in /da5_fast/All.sha1c/commit_127.tch'}

 71%|███████████████████████████████████████████████████████                       | 1839/2608 [31:56<13:28,  1.05s/it]

Got Errors {'7fb3c2ad22b239913c37f5dab1f008c62e5ac2fb': 'Key 7fb3c2ad22b239913c37f5dab1f008c62e5ac2fb not found in /da5_fast/All.sha1c/commit_127.tch'}

 71%|███████████████████████████████████████████████████████                       | 1840/2608 [31:57<13:25,  1.05s/it]

Got Errors {'8002096658715f2f99bd5893a4d199c4f206f7cc': 'Key 8002096658715f2f99bd5893a4d199c4f206f7cc not found in /da5_fast/All.sha1c/commit_0.tch'}

 71%|███████████████████████████████████████████████████████                       | 1841/2608 [31:58<13:22,  1.05s/it]

Got Errors {'803101672253791bde08dddde4849e6a74db17ab': 'Key 803101672253791bde08dddde4849e6a74db17ab not found in /da5_fast/All.sha1c/commit_0.tch'}

 71%|███████████████████████████████████████████████████████▏                      | 1847/2608 [32:04<13:09,  1.04s/it]

Got Errors {'811bc49854c28694f9203710f71a25e894eb78d4': 'Key 811bc49854c28694f9203710f71a25e894eb78d4 not found in /da5_fast/All.sha1c/commit_1.tch'}

 71%|███████████████████████████████████████████████████████▍                      | 1855/2608 [32:12<13:10,  1.05s/it]

Got Errors {'826cfb2008acf68366762b5e1ad8ff923d703777': 'Key 826cfb2008acf68366762b5e1ad8ff923d703777 not found in /da5_fast/All.sha1c/commit_2.tch'}

 72%|███████████████████████████████████████████████████████▉                      | 1870/2608 [32:28<12:48,  1.04s/it]

Got Errors {'853690e1a191f14395396ac20da1fef55422e27e': 'Key 853690e1a191f14395396ac20da1fef55422e27e not found in /da5_fast/All.sha1c/commit_5.tch'}

 72%|████████████████████████████████████████████████████████▏                     | 1878/2608 [32:36<12:42,  1.04s/it]

Got Errors {'868a1ff6037de771e854d663c17d372ee3fb254d': 'Key 868a1ff6037de771e854d663c17d372ee3fb254d not found in /da5_fast/All.sha1c/commit_6.tch'}

 73%|████████████████████████████████████████████████████████▌                     | 1891/2608 [32:50<12:27,  1.04s/it]

Got Errors {'888f0af53842e36af889b80a5a88436db8220808': 'Key 888f0af53842e36af889b80a5a88436db8220808 not found in /da5_fast/All.sha1c/commit_8.tch'}

 73%|████████████████████████████████████████████████████████▌                     | 1892/2608 [32:51<12:25,  1.04s/it]

Got Errors {'8899ffa277341a69608bee96c91d7c2285e6161c': 'Key 8899ffa277341a69608bee96c91d7c2285e6161c not found in /da5_fast/All.sha1c/commit_8.tch'}

 73%|████████████████████████████████████████████████████████▌                     | 1893/2608 [32:52<12:24,  1.04s/it]

Got Errors {'88c5ea1acfb33cd5ca29e220e711fbc10a69fb53': 'Key 88c5ea1acfb33cd5ca29e220e711fbc10a69fb53 not found in /da5_fast/All.sha1c/commit_8.tch'}

 73%|████████████████████████████████████████████████████████▋                     | 1894/2608 [32:53<12:24,  1.04s/it]

Got Errors {'88f370c56a0702d50036f47d778b9e98a5ba5223': 'Key 88f370c56a0702d50036f47d778b9e98a5ba5223 not found in /da5_fast/All.sha1c/commit_8.tch'}

 73%|████████████████████████████████████████████████████████▉                     | 1904/2608 [33:03<12:12,  1.04s/it]

Got Errors {'8ab23c3a2487e1591b6115b69e0ab14bf743493b': 'Key 8ab23c3a2487e1591b6115b69e0ab14bf743493b not found in /da5_fast/All.sha1c/commit_10.tch'}

 73%|█████████████████████████████████████████████████████████                     | 1909/2608 [33:09<12:11,  1.05s/it]

Got Errors {'8ba9d5746d0fc0634501bf70f0f390cb05f6d1ad': 'Key 8ba9d5746d0fc0634501bf70f0f390cb05f6d1ad not found in /da5_fast/All.sha1c/commit_11.tch'}

 73%|█████████████████████████████████████████████████████████                     | 1910/2608 [33:10<12:06,  1.04s/it]

Got Errors {'8bd277a0a1b7b127eb3e3062f3cd9e9964bac6ac': 'Key 8bd277a0a1b7b127eb3e3062f3cd9e9964bac6ac not found in /da5_fast/All.sha1c/commit_11.tch'}

 74%|█████████████████████████████████████████████████████████▍                    | 1922/2608 [33:22<12:03,  1.06s/it]

Got Errors {'8e15e88ea4babb9a955ca646a6ca71a65a051b65': 'Key 8e15e88ea4babb9a955ca646a6ca71a65a051b65 not found in /da5_fast/All.sha1c/commit_14.tch'}

 74%|█████████████████████████████████████████████████████████▋                    | 1928/2608 [33:28<11:53,  1.05s/it]

Got Errors {'8ef5645f591bf65108b3b9bf068c0e525d0385d8': 'Key 8ef5645f591bf65108b3b9bf068c0e525d0385d8 not found in /da5_fast/All.sha1c/commit_14.tch'}

 74%|█████████████████████████████████████████████████████████▉                    | 1939/2608 [33:40<11:47,  1.06s/it]

Got Errors {'90eaba075e564dcfae48656ebf4f2b8ac88b8c41': 'Key 90eaba075e564dcfae48656ebf4f2b8ac88b8c41 not found in /da5_fast/All.sha1c/commit_16.tch'}

 75%|██████████████████████████████████████████████████████████▏                   | 1944/2608 [33:45<11:30,  1.04s/it]

Got Errors {'9160f8b4c42834752ccf5accf76202b03dcda059': 'Key 9160f8b4c42834752ccf5accf76202b03dcda059 not found in /da5_fast/All.sha1c/commit_17.tch', '916f60d2984c01eda311e05589b978ba8b5ad37c': 'Key 916f60d2984c01eda311e05589b978ba8b5ad37c not found in /da5_fast/All.sha1c/commit_17.tch'}

 75%|██████████████████████████████████████████████████████████▏                   | 1946/2608 [33:47<11:30,  1.04s/it]

Got Errors {'91cd3b43b37b32e3125759e2ac64f18c71845239': 'Key 91cd3b43b37b32e3125759e2ac64f18c71845239 not found in /da5_fast/All.sha1c/commit_17.tch'}

 75%|██████████████████████████████████████████████████████████▍                   | 1954/2608 [33:56<11:20,  1.04s/it]

Got Errors {'938598c393e73bc72041c5a27a0e66bf2e66fc1f': 'Key 938598c393e73bc72041c5a27a0e66bf2e66fc1f not found in /da5_fast/All.sha1c/commit_19.tch'}

 75%|██████████████████████████████████████████████████████████▌                   | 1956/2608 [33:58<11:17,  1.04s/it]

Got Errors {'93ea1acc997cca5f0866af4b5a1b3a2306a0d2b2': 'Key 93ea1acc997cca5f0866af4b5a1b3a2306a0d2b2 not found in /da5_fast/All.sha1c/commit_19.tch'}

 75%|██████████████████████████████████████████████████████████▊                   | 1966/2608 [34:08<11:10,  1.04s/it]

Got Errors {'95698e7e09f4edf5c50ccaf1ffc14130120a1ede': 'Key 95698e7e09f4edf5c50ccaf1ffc14130120a1ede not found in /da5_fast/All.sha1c/commit_21.tch'}

 77%|███████████████████████████████████████████████████████████▊                  | 1999/2608 [34:42<10:31,  1.04s/it]

Got Errors {'9abad88d46f7e2fa7f31f8f05a9bf814ca833dbd': 'Key 9abad88d46f7e2fa7f31f8f05a9bf814ca833dbd not found in /da5_fast/All.sha1c/commit_26.tch', '9acdcc1da387d9066e3d18bb97ebe695616b3c6c': 'Key 9acdcc1da387d9066e3d18bb97ebe695616b3c6c not found in /da5_fast/All.sha1c/commit_26.tch'}

 77%|███████████████████████████████████████████████████████████▉                  | 2002/2608 [34:46<10:29,  1.04s/it]

Got Errors {'9b452f41a7709a92d4bc68cdfa0d163371fa58f2': 'Key 9b452f41a7709a92d4bc68cdfa0d163371fa58f2 not found in /da5_fast/All.sha1c/commit_27.tch'}

 77%|████████████████████████████████████████████████████████████▏                 | 2012/2608 [34:56<10:18,  1.04s/it]

Got Errors {'9cbb7398b13cadb4b795c29173176940ee6c5d34': 'Key 9cbb7398b13cadb4b795c29173176940ee6c5d34 not found in /da5_fast/All.sha1c/commit_28.tch'}

 78%|████████████████████████████████████████████████████████████▌                 | 2023/2608 [35:07<10:06,  1.04s/it]

Got Errors {'9e82dccc827ec9ed6cd20962e7d1fdc1ce06d33b': 'Key 9e82dccc827ec9ed6cd20962e7d1fdc1ce06d33b not found in /da5_fast/All.sha1c/commit_30.tch'}

 78%|████████████████████████████████████████████████████████████▋                 | 2028/2608 [35:13<10:00,  1.04s/it]

Got Errors {'9f65529cb58e886e800b98f9e8756f2b5f048a51': 'Key 9f65529cb58e886e800b98f9e8756f2b5f048a51 not found in /da5_fast/All.sha1c/commit_31.tch'}

 78%|████████████████████████████████████████████████████████████▊                 | 2035/2608 [35:20<09:54,  1.04s/it]

Got Errors {'a06471136956b7857e1b4ea48aba4a80792e2431': 'Key a06471136956b7857e1b4ea48aba4a80792e2431 not found in /da5_fast/All.sha1c/commit_32.tch'}

 78%|████████████████████████████████████████████████████████████▉                 | 2039/2608 [35:24<09:49,  1.04s/it]

Got Errors {'a1260a31932a269ae8c3c808cff1e5588998837b': 'Key a1260a31932a269ae8c3c808cff1e5588998837b not found in /da5_fast/All.sha1c/commit_33.tch'}

 78%|█████████████████████████████████████████████████████████████                 | 2041/2608 [35:26<09:47,  1.04s/it]

Got Errors {'a1558d52a694d6b8435eb85661f0d13b0a1a6fea': 'Key a1558d52a694d6b8435eb85661f0d13b0a1a6fea not found in /da5_fast/All.sha1c/commit_33.tch'}

 79%|█████████████████████████████████████████████████████████████▎                | 2048/2608 [35:33<09:40,  1.04s/it]

Got Errors {'a2bfb2cb967c8a3925c74e4039bfc60f136128c2': 'Key a2bfb2cb967c8a3925c74e4039bfc60f136128c2 not found in /da5_fast/All.sha1c/commit_34.tch'}

 79%|█████████████████████████████████████████████████████████████▋                | 2061/2608 [35:47<09:27,  1.04s/it]

Got Errors {'a4dc574ad34bea83045fa5275da4e8b52a348c8e': 'Key a4dc574ad34bea83045fa5275da4e8b52a348c8e not found in /da5_fast/All.sha1c/commit_36.tch'}

 79%|█████████████████████████████████████████████████████████████▊                | 2066/2608 [35:52<09:23,  1.04s/it]

Got Errors {'a5e56ce0c1fc2fca9fc07b26c326aed4f03f7f86': 'Key a5e56ce0c1fc2fca9fc07b26c326aed4f03f7f86 not found in /da5_fast/All.sha1c/commit_37.tch', 'a5f6d1475c975999610c8f05e1655ac6758c2c66': 'Key a5f6d1475c975999610c8f05e1655ac6758c2c66 not found in /da5_fast/All.sha1c/commit_37.tch'}

 80%|██████████████████████████████████████████████████████████████                | 2076/2608 [36:02<09:12,  1.04s/it]

Got Errors {'a7773e7668edb2daae03f66d0ce50714c895c486': 'Key a7773e7668edb2daae03f66d0ce50714c895c486 not found in /da5_fast/All.sha1c/commit_39.tch'}

 80%|██████████████████████████████████████████████████████████████▏               | 2080/2608 [36:07<09:07,  1.04s/it]

Got Errors {'a8463cf0b3b27a20019e31a4656f9615f32fd251': 'Key a8463cf0b3b27a20019e31a4656f9615f32fd251 not found in /da5_fast/All.sha1c/commit_40.tch'}

 80%|██████████████████████████████████████████████████████████████▎               | 2083/2608 [36:10<09:03,  1.04s/it]

Got Errors {'a8cac389a14f73d313852bb0b233b3fdce7817cb': 'Key a8cac389a14f73d313852bb0b233b3fdce7817cb not found in /da5_fast/All.sha1c/commit_40.tch'}

 80%|██████████████████████████████████████████████████████████████▋               | 2094/2608 [36:21<08:53,  1.04s/it]

Got Errors {'aa9c7843075a91e864381d421f9229a2703d5838': 'Key aa9c7843075a91e864381d421f9229a2703d5838 not found in /da5_fast/All.sha1c/commit_42.tch'}

 81%|██████████████████████████████████████████████████████████████▉               | 2103/2608 [36:30<08:43,  1.04s/it]

Got Errors {'ac7dc122874acbdd26599a5ebc049e57c30368bf': 'Key ac7dc122874acbdd26599a5ebc049e57c30368bf not found in /da5_fast/All.sha1c/commit_44.tch'}

 81%|██████████████████████████████████████████████████████████████▉               | 2105/2608 [36:32<08:41,  1.04s/it]

Got Errors {'acd916bd192f3b281ab7da0c1924f6e801f86c47': 'Key acd916bd192f3b281ab7da0c1924f6e801f86c47 not found in /da5_fast/All.sha1c/commit_44.tch'}

 81%|███████████████████████████████████████████████████████████████               | 2107/2608 [36:35<08:39,  1.04s/it]

Got Errors {'ad26315badb42b97996e47921d65b7078a67cc62': 'Key ad26315badb42b97996e47921d65b7078a67cc62 not found in /da5_fast/All.sha1c/commit_45.tch'}

 81%|███████████████████████████████████████████████████████████████▎              | 2116/2608 [36:44<08:30,  1.04s/it]

Got Errors {'ae59743117ad58438f06bc563fe0af94e54fc310': 'Key ae59743117ad58438f06bc563fe0af94e54fc310 not found in /da5_fast/All.sha1c/commit_46.tch'}

 81%|███████████████████████████████████████████████████████████████▎              | 2117/2608 [36:45<08:29,  1.04s/it]

Got Errors {'ae90789a10d9031e006f71a5c89d34539ea2e1e5': 'Key ae90789a10d9031e006f71a5c89d34539ea2e1e5 not found in /da5_fast/All.sha1c/commit_46.tch'}

 82%|███████████████████████████████████████████████████████████████▋              | 2129/2608 [36:57<08:17,  1.04s/it]

Got Errors {'b0b2e0b45c00282f49d10849abf567f0fb5f5434': 'Key b0b2e0b45c00282f49d10849abf567f0fb5f5434 not found in /da5_fast/All.sha1c/commit_48.tch'}

 82%|███████████████████████████████████████████████████████████████▊              | 2132/2608 [37:00<08:15,  1.04s/it]

Got Errors {'b16d8bf3a1e4b3a09dcab07bdeba15de3c4324f3': 'Key b16d8bf3a1e4b3a09dcab07bdeba15de3c4324f3 not found in /da5_fast/All.sha1c/commit_49.tch'}

 82%|███████████████████████████████████████████████████████████████▉              | 2137/2608 [37:06<08:09,  1.04s/it]

Got Errors {'b225917152074841d10e97562799bba28aa2d21c': 'Key b225917152074841d10e97562799bba28aa2d21c not found in /da5_fast/All.sha1c/commit_50.tch'}

 82%|███████████████████████████████████████████████████████████████▉              | 2139/2608 [37:08<08:07,  1.04s/it]

Got Errors {'b27703b6c91cb285b62f7eb55fab400badb247a8': 'Key b27703b6c91cb285b62f7eb55fab400badb247a8 not found in /da5_fast/All.sha1c/commit_50.tch'}

 83%|████████████████████████████████████████████████████████████████▍             | 2153/2608 [37:22<07:52,  1.04s/it]

Got Errors {'b4afecb03ced1c95f1bb4f9f25ea965dce41b4d5': 'Key b4afecb03ced1c95f1bb4f9f25ea965dce41b4d5 not found in /da5_fast/All.sha1c/commit_52.tch'}

 83%|████████████████████████████████████████████████████████████████▌             | 2157/2608 [37:26<07:48,  1.04s/it]

Got Errors {'b5339cdd587c85401337af029f00e566bbca4202': 'Key b5339cdd587c85401337af029f00e566bbca4202 not found in /da5_fast/All.sha1c/commit_53.tch'}

 83%|████████████████████████████████████████████████████████████████▉             | 2171/2608 [37:41<07:33,  1.04s/it]

Got Errors {'b78a1759c82091f630f6a984aea4a3a71b30cffc': 'Key b78a1759c82091f630f6a984aea4a3a71b30cffc not found in /da5_fast/All.sha1c/commit_55.tch'}

 83%|█████████████████████████████████████████████████████████████████             | 2176/2608 [37:46<07:27,  1.04s/it]

Got Errors {'b85febc8e07a72b36cba3e1eb64b3a1996376823': 'Key b85febc8e07a72b36cba3e1eb64b3a1996376823 not found in /da5_fast/All.sha1c/commit_56.tch'}

 84%|█████████████████████████████████████████████████████████████████▍            | 2186/2608 [37:57<07:29,  1.06s/it]

Got Errors {'ba3e8661a414e9efaa1b9d93fced4fd8d8552f42': 'Key ba3e8661a414e9efaa1b9d93fced4fd8d8552f42 not found in /da5_fast/All.sha1c/commit_58.tch'}

 84%|█████████████████████████████████████████████████████████████████▍            | 2188/2608 [37:59<07:22,  1.05s/it]

Got Errors {'ba93ff4672d98e270e5f18b6eeb74d6773ee00c1': 'Key ba93ff4672d98e270e5f18b6eeb74d6773ee00c1 not found in /da5_fast/All.sha1c/commit_58.tch'}

 84%|█████████████████████████████████████████████████████████████████▌            | 2191/2608 [38:02<07:16,  1.05s/it]

Got Errors {'bb3a3d94b1ef1cfb91c7b2b174333ac8ec9e7f64': 'Key bb3a3d94b1ef1cfb91c7b2b174333ac8ec9e7f64 not found in /da5_fast/All.sha1c/commit_59.tch', 'bb3fc8d90f546a8c6fdaf6f45fed57bb518c7b60': 'Key bb3fc8d90f546a8c6fdaf6f45fed57bb518c7b60 not found in /da5_fast/All.sha1c/commit_59.tch'}

 84%|█████████████████████████████████████████████████████████████████▊            | 2200/2608 [38:11<07:07,  1.05s/it]

Got Errors {'bca97e05fc99f9e961e783a8c242ff7bbc1aec96': 'Key bca97e05fc99f9e961e783a8c242ff7bbc1aec96 not found in /da5_fast/All.sha1c/commit_60.tch'}

 84%|█████████████████████████████████████████████████████████████████▊            | 2201/2608 [38:12<07:05,  1.05s/it]

Got Errors {'bcba92eb225d33172c52cdc4d21bdec8fa6ba85b': 'Key bcba92eb225d33172c52cdc4d21bdec8fa6ba85b not found in /da5_fast/All.sha1c/commit_60.tch'}

 85%|██████████████████████████████████████████████████████████████████▎           | 2217/2608 [38:29<06:48,  1.04s/it]

Got Errors {'bf7df9c7ac42cfef0c128e7824bb69c487df98a9': 'Key bf7df9c7ac42cfef0c128e7824bb69c487df98a9 not found in /da5_fast/All.sha1c/commit_63.tch'}

 85%|██████████████████████████████████████████████████████████████████▍           | 2223/2608 [38:35<06:41,  1.04s/it]

Got Errors {'c0695de637c109a809e1e5d9f9a77a135d8b2550': 'Key c0695de637c109a809e1e5d9f9a77a135d8b2550 not found in /da5_fast/All.sha1c/commit_64.tch'}

 86%|██████████████████████████████████████████████████████████████████▊           | 2233/2608 [38:46<06:31,  1.04s/it]

Got Errors {'c20a5bc8b0615951712658ce7883823b40bbfd01': 'Key c20a5bc8b0615951712658ce7883823b40bbfd01 not found in /da5_fast/All.sha1c/commit_66.tch'}

 86%|██████████████████████████████████████████████████████████████████▉           | 2237/2608 [38:50<06:28,  1.05s/it]

Got Errors {'c2b454e0a0a10e8417b4f9af1658edfbf8993499': 'Key c2b454e0a0a10e8417b4f9af1658edfbf8993499 not found in /da5_fast/All.sha1c/commit_66.tch', 'c2c8605b2e3436aa1489974920ff02fffe3d743c': 'Key c2c8605b2e3436aa1489974920ff02fffe3d743c not found in /da5_fast/All.sha1c/commit_66.tch'}

 86%|███████████████████████████████████████████████████████████████████           | 2241/2608 [38:54<06:26,  1.05s/it]

Got Errors {'c34297a82db6e83a4bccdc6ce479d6c69ea536c4': 'Key c34297a82db6e83a4bccdc6ce479d6c69ea536c4 not found in /da5_fast/All.sha1c/commit_67.tch'}

 86%|███████████████████████████████████████████████████████████████████▏          | 2248/2608 [39:01<06:13,  1.04s/it]

Got Errors {'c4b3e70c490251681048b634d89c62d089a9a204': 'Key c4b3e70c490251681048b634d89c62d089a9a204 not found in /da5_fast/All.sha1c/commit_68.tch'}

 86%|███████████████████████████████████████████████████████████████████▎          | 2252/2608 [39:06<06:13,  1.05s/it]

Got Errors {'c57194d1f4ce3611feeac912db59142fe0d2398a': 'Key c57194d1f4ce3611feeac912db59142fe0d2398a not found in /da5_fast/All.sha1c/commit_69.tch'}

 87%|███████████████████████████████████████████████████████████████████▌          | 2257/2608 [39:11<06:07,  1.05s/it]

Got Errors {'c653cf1b0412d6272a7ff016e5ee7c12219a1483': 'Key c653cf1b0412d6272a7ff016e5ee7c12219a1483 not found in /da5_fast/All.sha1c/commit_70.tch'}

 87%|███████████████████████████████████████████████████████████████████▋          | 2262/2608 [39:16<06:00,  1.04s/it]

Got Errors {'c6ef1fe07fd19d2cb9b3b26386cbec7eca69e15e': 'Key c6ef1fe07fd19d2cb9b3b26386cbec7eca69e15e not found in /da5_fast/All.sha1c/commit_70.tch', 'c7052eec49e8360823b49eb321a4fcc49c08888a': 'Key c7052eec49e8360823b49eb321a4fcc49c08888a not found in /da5_fast/All.sha1c/commit_71.tch'}

 87%|███████████████████████████████████████████████████████████████████▋          | 2265/2608 [39:19<05:57,  1.04s/it]

Got Errors {'c76eb4c08555d55fdd54313f5fb25481d28d1150': 'Key c76eb4c08555d55fdd54313f5fb25481d28d1150 not found in /da5_fast/All.sha1c/commit_71.tch', 'c78d857768e959738bf60f4ff28cd299ba5689fe': 'Key c78d857768e959738bf60f4ff28cd299ba5689fe not found in /da5_fast/All.sha1c/commit_71.tch'}

 87%|████████████████████████████████████████████████████████████████████          | 2276/2608 [39:31<05:44,  1.04s/it]

Got Errors {'c943f4a4254cec65c29cbd5e366bb2ce5db85467': 'Key c943f4a4254cec65c29cbd5e366bb2ce5db85467 not found in /da5_fast/All.sha1c/commit_73.tch'}

 87%|████████████████████████████████████████████████████████████████████▏         | 2278/2608 [39:33<05:44,  1.04s/it]

Got Errors {'c9afb8d89b6feb44d2d1bb3ac5a31f148ade5b11': 'Key c9afb8d89b6feb44d2d1bb3ac5a31f148ade5b11 not found in /da5_fast/All.sha1c/commit_73.tch'}

 88%|████████████████████████████████████████████████████████████████████▎         | 2282/2608 [39:37<05:39,  1.04s/it]

Got Errors {'ca5f10168c23b979a9afe8e7611b9ae237cb9d72': 'Key ca5f10168c23b979a9afe8e7611b9ae237cb9d72 not found in /da5_fast/All.sha1c/commit_74.tch'}

 88%|████████████████████████████████████████████████████████████████████▍         | 2287/2608 [39:42<05:33,  1.04s/it]

Got Errors {'cb46d231f7fdd7e2ebfc93b4124525684f1f352e': 'Key cb46d231f7fdd7e2ebfc93b4124525684f1f352e not found in /da5_fast/All.sha1c/commit_75.tch'}

 88%|████████████████████████████████████████████████████████████████████▌         | 2291/2608 [39:46<05:31,  1.05s/it]

Got Errors {'cbfc657406186a18c7233602a2ecf3e79024bca7': 'Key cbfc657406186a18c7233602a2ecf3e79024bca7 not found in /da5_fast/All.sha1c/commit_75.tch'}

 88%|████████████████████████████████████████████████████████████████████▌         | 2292/2608 [39:47<05:30,  1.05s/it]

Got Errors {'cc32112384a95de94907d31b3001855a94b23fd3': 'Key cc32112384a95de94907d31b3001855a94b23fd3 not found in /da5_fast/All.sha1c/commit_76.tch'}

 88%|████████████████████████████████████████████████████████████████████▋         | 2298/2608 [39:54<05:22,  1.04s/it]

Got Errors {'cd1660a625594903e4f5a01cda8ecfb9da487237': 'Key cd1660a625594903e4f5a01cda8ecfb9da487237 not found in /da5_fast/All.sha1c/commit_77.tch'}

 88%|████████████████████████████████████████████████████████████████████▊         | 2301/2608 [39:57<05:20,  1.04s/it]

Got Errors {'cd4b992453d13684e1abdfc782731323c4ed6e9c': 'Key cd4b992453d13684e1abdfc782731323c4ed6e9c not found in /da5_fast/All.sha1c/commit_77.tch'}

 89%|█████████████████████████████████████████████████████████████████████▏        | 2313/2608 [40:09<05:07,  1.04s/it]

Got Errors {'cf7867f41800394e2492bd0418bfc13d584dcdfe': 'Key cf7867f41800394e2492bd0418bfc13d584dcdfe not found in /da5_fast/All.sha1c/commit_79.tch'}

 89%|█████████████████████████████████████████████████████████████████████▎        | 2319/2608 [40:15<05:02,  1.05s/it]

Got Errors {'d076d0ac5fb4208930ddf3190cb09f1ee0ebe3a2': 'Key d076d0ac5fb4208930ddf3190cb09f1ee0ebe3a2 not found in /da5_fast/All.sha1c/commit_80.tch'}

 89%|█████████████████████████████████████████████████████████████████████▌        | 2326/2608 [40:23<04:52,  1.04s/it]

Got Errors {'d19a5fd99179e47beb947fbba45a067263762f48': 'Key d19a5fd99179e47beb947fbba45a067263762f48 not found in /da5_fast/All.sha1c/commit_81.tch', 'd1aec1877ef56372da3019482d2ac67d24fb5ead': 'Key d1aec1877ef56372da3019482d2ac67d24fb5ead not found in /da5_fast/All.sha1c/commit_81.tch'}

 89%|█████████████████████████████████████████████████████████████████████▋        | 2328/2608 [40:25<04:51,  1.04s/it]

Got Errors {'d1f69b96fcc4d372aeef36a6dd59e51c6130e8c2': 'Key d1f69b96fcc4d372aeef36a6dd59e51c6130e8c2 not found in /da5_fast/All.sha1c/commit_81.tch', 'd1fbab86677b02007418ee5bccb28d82078ef4a3': 'Key d1fbab86677b02007418ee5bccb28d82078ef4a3 not found in /da5_fast/All.sha1c/commit_81.tch'}

 89%|█████████████████████████████████████████████████████████████████████▋        | 2329/2608 [40:26<04:51,  1.04s/it]

Got Errors {'d2181d28198c1942aeb99b565c509e88d4ef476e': 'Key d2181d28198c1942aeb99b565c509e88d4ef476e not found in /da5_fast/All.sha1c/commit_82.tch'}

 90%|█████████████████████████████████████████████████████████████████████▉        | 2338/2608 [40:35<04:42,  1.04s/it]

Got Errors {'d3ca09187650da93c7f84a7ffbec0f662eb3fe1b': 'Key d3ca09187650da93c7f84a7ffbec0f662eb3fe1b not found in /da5_fast/All.sha1c/commit_83.tch'}

 90%|██████████████████████████████████████████████████████████████████████▏       | 2346/2608 [40:44<04:33,  1.04s/it]

Got Errors {'d543e41dbd3bdcc96bd04960e955a2cd4dbc7831': 'Key d543e41dbd3bdcc96bd04960e955a2cd4dbc7831 not found in /da5_fast/All.sha1c/commit_85.tch'}

 90%|██████████████████████████████████████████████████████████████████████▍       | 2357/2608 [40:55<04:22,  1.05s/it]

Got Errors {'d6bc51e43b46c918183bd5cf906d0868eeb6510d': 'Key d6bc51e43b46c918183bd5cf906d0868eeb6510d not found in /da5_fast/All.sha1c/commit_86.tch'}

 91%|██████████████████████████████████████████████████████████████████████▋       | 2363/2608 [41:02<04:17,  1.05s/it]

Got Errors {'d7ba18e94d2e4c7a1086c1ca6dab56dd0ab924d5': 'Key d7ba18e94d2e4c7a1086c1ca6dab56dd0ab924d5 not found in /da5_fast/All.sha1c/commit_87.tch', 'd7d0f4fff41424be9caece2bbfe688be94bd7811': 'Key d7d0f4fff41424be9caece2bbfe688be94bd7811 not found in /da5_fast/All.sha1c/commit_87.tch'}

 91%|██████████████████████████████████████████████████████████████████████▋       | 2364/2608 [41:03<04:15,  1.05s/it]

Got Errors {'d8369de77e327dd46fd795684cc0b0bf8cdcf224': 'Key d8369de77e327dd46fd795684cc0b0bf8cdcf224 not found in /da5_fast/All.sha1c/commit_88.tch'}

 91%|██████████████████████████████████████████████████████████████████████▊       | 2369/2608 [41:08<04:10,  1.05s/it]

Got Errors {'d8edaffaccc7c2b345dab34f71fc502ff3b9c8d0': 'Key d8edaffaccc7c2b345dab34f71fc502ff3b9c8d0 not found in /da5_fast/All.sha1c/commit_88.tch'}

 91%|███████████████████████████████████████████████████████████████████████       | 2375/2608 [41:14<04:01,  1.04s/it]

Got Errors {'da1ddfdf00cbd3773f9d14b2e452c65ff7a7df7c': 'Key da1ddfdf00cbd3773f9d14b2e452c65ff7a7df7c not found in /da5_fast/All.sha1c/commit_90.tch'}

 91%|███████████████████████████████████████████████████████████████████████▏      | 2382/2608 [41:21<03:57,  1.05s/it]

Got Errors {'db377a5d7574efbe5b03f4b750c97d26facd0224': 'Key db377a5d7574efbe5b03f4b750c97d26facd0224 not found in /da5_fast/All.sha1c/commit_91.tch'}

 92%|███████████████████████████████████████████████████████████████████████▍      | 2387/2608 [41:27<03:49,  1.04s/it]

Got Errors {'dbea91b60d24a012899d453cd59c236a18dac786': 'Key dbea91b60d24a012899d453cd59c236a18dac786 not found in /da5_fast/All.sha1c/commit_91.tch', 'dbeade3de68ebc88ca0b6ce72297b3b609c5a387': 'Key dbeade3de68ebc88ca0b6ce72297b3b609c5a387 not found in /da5_fast/All.sha1c/commit_91.tch'}

 92%|███████████████████████████████████████████████████████████████████████▌      | 2391/2608 [41:31<03:45,  1.04s/it]

Got Errors {'dc9c10e5fd752db9cd3f2fe5bb7b44048ab95a16': 'Key dc9c10e5fd752db9cd3f2fe5bb7b44048ab95a16 not found in /da5_fast/All.sha1c/commit_92.tch'}

 92%|███████████████████████████████████████████████████████████████████████▊      | 2400/2608 [41:40<03:37,  1.05s/it]

Got Errors {'ddfaa2c227594478da99837608886ed4d968ba2a': 'Key ddfaa2c227594478da99837608886ed4d968ba2a not found in /da5_fast/All.sha1c/commit_93.tch'}

 92%|████████████████████████████████████████████████████████████████████████      | 2408/2608 [41:48<03:28,  1.04s/it]

Got Errors {'df2b658115a72b29e6545c3dc8700bcc8491c2af': 'Key df2b658115a72b29e6545c3dc8700bcc8491c2af not found in /da5_fast/All.sha1c/commit_95.tch'}

 93%|████████████████████████████████████████████████████████████████████████▎     | 2416/2608 [41:57<03:21,  1.05s/it]

Got Errors {'e0bd5365ded3ca51340d536801463e41df28482d': 'Key e0bd5365ded3ca51340d536801463e41df28482d not found in /da5_fast/All.sha1c/commit_96.tch'}

 93%|████████████████████████████████████████████████████████████████████████▎     | 2418/2608 [41:59<03:18,  1.05s/it]

Got Errors {'e10d6524cc2ec3c27a185e3b3a784d5b8dab41cb': 'Key e10d6524cc2ec3c27a185e3b3a784d5b8dab41cb not found in /da5_fast/All.sha1c/commit_97.tch'}

 93%|████████████████████████████████████████████████████████████████████████▍     | 2421/2608 [42:02<03:14,  1.04s/it]

Got Errors {'e176cee9e1cf513873f8b04d0dd1bf5d01c169cc': 'Key e176cee9e1cf513873f8b04d0dd1bf5d01c169cc not found in /da5_fast/All.sha1c/commit_97.tch'}

 94%|█████████████████████████████████████████████████████████████████████████▏    | 2449/2608 [42:31<02:46,  1.05s/it]

Got Errors {'e61c7795d56e56dfc0fe1bd7bca035594950d94f': 'Key e61c7795d56e56dfc0fe1bd7bca035594950d94f not found in /da5_fast/All.sha1c/commit_102.tch'}

 94%|█████████████████████████████████████████████████████████████████████████▎    | 2450/2608 [42:32<02:45,  1.05s/it]

Got Errors {'e628cf00e1d363a2cc077a5221c3bf1d0b262592': 'Key e628cf00e1d363a2cc077a5221c3bf1d0b262592 not found in /da5_fast/All.sha1c/commit_102.tch'}

 94%|█████████████████████████████████████████████████████████████████████████▋    | 2462/2608 [42:45<02:31,  1.04s/it]

Got Errors {'e81b95bef4632c58e06e0bcf47e838788f2f418d': 'Key e81b95bef4632c58e06e0bcf47e838788f2f418d not found in /da5_fast/All.sha1c/commit_104.tch', 'e81bb1f90770802b18f44dbfbdb9f2d519c259a4': 'Key e81bb1f90770802b18f44dbfbdb9f2d519c259a4 not found in /da5_fast/All.sha1c/commit_104.tch'}

 95%|█████████████████████████████████████████████████████████████████████████▋    | 2465/2608 [42:48<02:29,  1.04s/it]

Got Errors {'e8b3b839ccfa285d9d8a74ca84287cbf8c7236ad': 'Key e8b3b839ccfa285d9d8a74ca84287cbf8c7236ad not found in /da5_fast/All.sha1c/commit_104.tch'}

 95%|█████████████████████████████████████████████████████████████████████████▉    | 2472/2608 [42:55<02:21,  1.04s/it]

Got Errors {'e9dba77a61753fedd6f05577ef5a6d464a6c555f': 'Key e9dba77a61753fedd6f05577ef5a6d464a6c555f not found in /da5_fast/All.sha1c/commit_105.tch'}

 95%|██████████████████████████████████████████████████████████████████████████    | 2475/2608 [42:58<02:19,  1.05s/it]

Got Errors {'ea3f49efdb8291a5a8a90e402337e9f6152b51de': 'Key ea3f49efdb8291a5a8a90e402337e9f6152b51de not found in /da5_fast/All.sha1c/commit_106.tch'}

 95%|██████████████████████████████████████████████████████████████████████████▏   | 2480/2608 [43:04<02:13,  1.04s/it]

Got Errors {'eac9f747b4c7e695994e7dc8cbfb559c34eb4a6b': 'Key eac9f747b4c7e695994e7dc8cbfb559c34eb4a6b not found in /da5_fast/All.sha1c/commit_106.tch'}

 95%|██████████████████████████████████████████████████████████████████████████▏   | 2482/2608 [43:06<02:11,  1.04s/it]

Got Errors {'eb2cd7d7085419ca89769b6726a6019e56cfc301': 'Key eb2cd7d7085419ca89769b6726a6019e56cfc301 not found in /da5_fast/All.sha1c/commit_107.tch'}

 95%|██████████████████████████████████████████████████████████████████████████▎   | 2483/2608 [43:07<02:10,  1.04s/it]

Got Errors {'eb46711b26f4e139cf1edb58ea4e8b12a09ff91e': 'Key eb46711b26f4e139cf1edb58ea4e8b12a09ff91e not found in /da5_fast/All.sha1c/commit_107.tch'}

 95%|██████████████████████████████████████████████████████████████████████████▍   | 2489/2608 [43:13<02:03,  1.04s/it]

Got Errors {'ec240b9b9b4cdc990382a28cf2404bab77512fca': 'Key ec240b9b9b4cdc990382a28cf2404bab77512fca not found in /da5_fast/All.sha1c/commit_108.tch', 'ec24b84b55c7d827fa8e00f81e8bb9d3d25382b5': 'Key ec24b84b55c7d827fa8e00f81e8bb9d3d25382b5 not found in /da5_fast/All.sha1c/commit_108.tch'}

 96%|██████████████████████████████████████████████████████████████████████████▉   | 2507/2608 [43:32<01:45,  1.04s/it]

Got Errors {'ef97a5738712eed321d1fee74ae049d2e40ff0bc': 'Key ef97a5738712eed321d1fee74ae049d2e40ff0bc not found in /da5_fast/All.sha1c/commit_111.tch'}

 96%|███████████████████████████████████████████████████████████████████████████   | 2509/2608 [43:34<01:43,  1.05s/it]

Got Errors {'efd8e050b182423d1054fcab6bbb7b6f2f475c9e': 'Key efd8e050b182423d1054fcab6bbb7b6f2f475c9e not found in /da5_fast/All.sha1c/commit_111.tch'}

 97%|███████████████████████████████████████████████████████████████████████████▎  | 2518/2608 [43:43<01:33,  1.04s/it]

Got Errors {'f169b5a17157117e7fbfe31fd48af68d1496258c': 'Key f169b5a17157117e7fbfe31fd48af68d1496258c not found in /da5_fast/All.sha1c/commit_113.tch'}

 97%|███████████████████████████████████████████████████████████████████████████▍  | 2524/2608 [43:50<01:27,  1.04s/it]

Got Errors {'f28fe96d62f1213c0aeb57b40e8e40889eb0811e': 'Key f28fe96d62f1213c0aeb57b40e8e40889eb0811e not found in /da5_fast/All.sha1c/commit_114.tch'}

 97%|███████████████████████████████████████████████████████████████████████████▋  | 2531/2608 [43:57<01:20,  1.04s/it]

Got Errors {'f386e1defcd17bfeaba7c3912c562a238e851d8a': 'Key f386e1defcd17bfeaba7c3912c562a238e851d8a not found in /da5_fast/All.sha1c/commit_115.tch'}

 97%|███████████████████████████████████████████████████████████████████████████▊  | 2536/2608 [44:02<01:14,  1.04s/it]

Got Errors {'f44e2ced77e49b5929323ae1101466997f168ba0': 'Key f44e2ced77e49b5929323ae1101466997f168ba0 not found in /da5_fast/All.sha1c/commit_116.tch'}

 97%|███████████████████████████████████████████████████████████████████████████▉  | 2538/2608 [44:04<01:13,  1.05s/it]

Got Errors {'f495e2dd7b8840580627029ea957b6d77560c16e': 'Key f495e2dd7b8840580627029ea957b6d77560c16e not found in /da5_fast/All.sha1c/commit_116.tch', 'f4983dcae390985b9d194202c27e6775f28023de': 'Key f4983dcae390985b9d194202c27e6775f28023de not found in /da5_fast/All.sha1c/commit_116.tch', 'f4acb3e0364a1e9f963b41cc66b3f7bd0de76c20': 'Key f4acb3e0364a1e9f963b41cc66b3f7bd0de76c20 not found in /da5_fast/All.sha1c/commit_116.tch'}

 97%|████████████████████████████████████████████████████████████████████████████  | 2542/2608 [44:08<01:08,  1.04s/it]

Got Errors {'f5236c9734a12e66e8c3fa3141896ea3639ca8cf': 'Key f5236c9734a12e66e8c3fa3141896ea3639ca8cf not found in /da5_fast/All.sha1c/commit_117.tch'}

 98%|████████████████████████████████████████████████████████████████████████████▏ | 2549/2608 [44:16<01:01,  1.04s/it]

Got Errors {'f64f547bc21887f3d84f302d948c476d5794623c': 'Key f64f547bc21887f3d84f302d948c476d5794623c not found in /da5_fast/All.sha1c/commit_118.tch'}

 98%|████████████████████████████████████████████████████████████████████████████▎ | 2552/2608 [44:19<00:58,  1.04s/it]

Got Errors {'f70838c6581084cf8401daf800ff7c14582ec11a': 'Key f70838c6581084cf8401daf800ff7c14582ec11a not found in /da5_fast/All.sha1c/commit_119.tch'}

 98%|████████████████████████████████████████████████████████████████████████████▍ | 2556/2608 [44:23<00:54,  1.04s/it]

Got Errors {'f78277f033f4b0bbf91492cf8c77dcb3d5e39950': 'Key f78277f033f4b0bbf91492cf8c77dcb3d5e39950 not found in /da5_fast/All.sha1c/commit_119.tch'}

 98%|████████████████████████████████████████████████████████████████████████████▍ | 2557/2608 [44:24<00:53,  1.04s/it]

Got Errors {'f7c743596e4f5c81f1f93e61849c937380d395d5': 'Key f7c743596e4f5c81f1f93e61849c937380d395d5 not found in /da5_fast/All.sha1c/commit_119.tch'}

 99%|█████████████████████████████████████████████████████████████████████████████ | 2577/2608 [44:45<00:32,  1.04s/it]

Got Errors {'fac951fae30427914fac0d5f21cc1711402ce236': 'Key fac951fae30427914fac0d5f21cc1711402ce236 not found in /da5_fast/All.sha1c/commit_122.tch'}

 99%|█████████████████████████████████████████████████████████████████████████████▍| 2588/2608 [44:56<00:20,  1.04s/it]

Got Errors {'fd003aed6feeccd6de6079e73039ab322b9652e9': 'Key fd003aed6feeccd6de6079e73039ab322b9652e9 not found in /da5_fast/All.sha1c/commit_125.tch'}

 99%|█████████████████████████████████████████████████████████████████████████████▌| 2592/2608 [45:00<00:16,  1.04s/it]

Got Errors {'fd8731b8272e4958c8231a6794a98a1874564a08': 'Key fd8731b8272e4958c8231a6794a98a1874564a08 not found in /da5_fast/All.sha1c/commit_125.tch'}

 99%|█████████████████████████████████████████████████████████████████████████████▌| 2593/2608 [45:01<00:15,  1.04s/it]

Got Errors {'fd92a8d9c4e7bc2a5d71a9f480fc22bb8b15d156': 'Key fd92a8d9c4e7bc2a5d71a9f480fc22bb8b15d156 not found in /da5_fast/All.sha1c/commit_125.tch'}

100%|█████████████████████████████████████████████████████████████████████████████▉| 2604/2608 [45:13<00:04,  1.04s/it]

Got Errors {'ff66e348fc6786a85f8ff8732f9876d63e3782d6': 'Key ff66e348fc6786a85f8ff8732f9876d63e3782d6 not found in /da5_fast/All.sha1c/commit_127.tch'}

100%|██████████████████████████████████████████████████████████████████████████████| 2608/2608 [45:17<00:00,  1.04s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0023779e992f3962eecf62e652ba81fe66da3852,5b8285fac196b42042d3cdc10490502feb433a0f,[849cfe159470e7600570cac179b8e69e2edc3e64],Robert Aboukhalil <robert.aboukhalil@gmail.com>,1584246680,-0700,Robert Aboukhalil <robert.aboukhalil@gmail.com>,1584246680,-0700,Small fix\n,0023779e992f3962eecf62e652ba81fe66da3852,marianattestad_ribbon
1,00c7ec6d1edf1ee4fef4e87b9e8254271f76fd2e,71c0c4a2afed052ec0621457b27f6dfa0cd5800d,"[240b6a5c8cea34909572fa8fd0c5d585dc0d5a78, a22...",Maria Nattestad <maria.nattestad@gmail.com>,1472156867,-0700,Maria Nattestad <maria.nattestad@gmail.com>,1472156867,-0700,Merge branch 'master' into web-production\n,00c7ec6d1edf1ee4fef4e87b9e8254271f76fd2e,marianattestad_ribbon

In [37]:
print("Original Number of Commits: ", len(df))
print("Recieved Number of Commits: ", len(df_commit_data))
print("Missing Number of Commits: ", len(df) - len(df_commit_data))

Original Number of Commits:  26071
Recieved Number of Commits:  25776
Missing Number of Commits:  295

In [38]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '0023779e992f3962eecf62e652ba81fe66da3852', 'tree': '5b8285fac196b42042d3cdc10490502feb433a0f', 'parent': ['849cfe159470e7600570cac179b8e69e2edc3e64'], 'author': 'Robert Aboukhalil <robert.aboukhalil@gmail.com>', 'author_time': 1584246680, 'author_tz': '-0700', 'committer': 'Robert Aboukhalil <robert.aboukhalil@gmail.com>', 'committer_time': 1584246680, 'committer_tz': '-0700', 'message': 'Small fix\n'}

In [44]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = df_commit_data[
    ['project', 'commit', 'author', 'author_time', 'message']
].copy()
dfinf = dfinf.rename(columns={
    'project': 'project_wocid',
    'commit': 'commit_sha1',
    'author_time': 'time',
    'message': 'commit_message'
})

print(dfinf['project_wocid'].value_counts())
print('\n')

dfinf.head(1)

project_wocid
xeokit_xeokit-sdk                                  14856
stan-dev_cmdstanpy                                  2742
jonescompneurolab_hnn                               2049
jhuapl-boss_intern                                  1471
mirnylab_cooler                                     1403
privefl_bigstatsr                                   1007
thelfer_mfrontgenericinterfacesupport                751
rveltz_piecewisedeterministicmarkovprocesses.jl      608
marianattestad_ribbon                                519
lpwgroup_crank                                       370
Name: count, dtype: int64

,project_wocid,commit_sha1,author,time,commit_message
0,marianattestad_ribbon,0023779e992f3962eecf62e652ba81fe66da3852,Robert Aboukhalil <robert.aboukhalil@gmail.com>,1584246680,Small fix\n

In [45]:
#mode a means append, so you have all your projects in the same file
yournetid='cdamron3'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False, sep=';')

In [48]:
woc_summary = dfinf.groupby('project_wocid').agg(
    commits=('commit_sha1', 'count'),
    authors=('author', 'nunique'),
    max_time=('time', 'max'),
    min_time=('time', 'min')
).reset_index()

woc_summary

,project_wocid,commits,authors,max_time,min_time
0,jhuapl-boss_intern,1471,45,1745859342,1443622463
1,jonescompneurolab_hnn,2049,39,1761687929,1487864695
2,lpwgroup_crank,370,27,1746254838,1520143708
3,marianattestad_ribbon,519,7,1751099438,1467246668
4,mirnylab_cooler,1403,47,1762187309,1447703659
5,privefl_bigstatsr,1007,13,1753781436,1473922251
6,rveltz_piecewisedeterministicmarkovprocesses.jl,608,14,1772783699,1450270615
7,stan-dev_cmdstanpy,2742,83,1762364056,1546473710
8,thelfer_mfrontgenericinterfacesupport,751,25,1762378091,1529498553
9,xeokit_xeokit-sdk,14856,116,1762378885,1543685191

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github