In [1]:
import pandas as pd
from pathlib import Path

MY_NETID = "cdamron3"
TEAMMATE_NETID = "ncash3"

VALIDATION_FILE = Path(f"{MY_NETID}_validation_log.csv")

df = pd.read_csv(VALIDATION_FILE, keep_default_na=False)

print(f"Total validation records: {len(df)}")
print(f"Disagreements: {(df['PreDiscussAgreementstatus(Yes/No)'] == 'No').sum()}")

display(df.head())

Total validation records: 50
Disagreements: 11

,WOCProjectID,ProjectOwnerNetID,ValidatorNetID,Field,AuthorValue,ValidatorValue,PreDiscussAgreementstatus(Yes/No),AdjudicatedValue,KeyEvidence,Comments
0,afeinstein20_eleanor,ncash3,cdamron3,HasRecovered,Yes,Yes,Yes,,Longest gap: 2023-06 to 2024-04 (11 months). C...,
1,algebraicjulia_catlab.jl,ncash3,cdamron3,HasRecovered,Yes,Yes,Yes,,Longest gap: 2019-04 to 2019-06 (3 months). Co...,
2,microprediction_timemachines,ncash3,cdamron3,HasRecovered,Yes,Yes,Yes,,Longest gap: 2023-07 to 2024-09 (15 months). C...,
3,ntustison_crosslong,ncash3,cdamron3,HasRecovered,No,No,Yes,,Longest gap: 2022-01 to 2025-06 (42 months). C...,
4,patwie_cppnumericalsolvers,ncash3,cdamron3,HasRecovered,Yes,Yes,Yes,,Longest gap: 2022-09 to 2023-12 (16 months). C...,

In [4]:
# Normalize values to ignore capitalization and extra spaces
def normalize(value):
    return " ".join(str(value).strip().lower().split())

# Update agreement statuses when values match
df.loc[
    df.apply(
        lambda row: normalize(row["AuthorValue"]) ==
                    normalize(row["ValidatorValue"]),
        axis=1
    ),
    "PreDiscussAgreementstatus(Yes/No)"
] = "Yes"

# Save the corrected Part 1 CSV
df.to_csv(VALIDATION_FILE, index=False)

print("Agreement statuses updated!")

Agreement statuses updated!

In [5]:
disagreements = df[
    df["PreDiscussAgreementstatus(Yes/No)"]
    .str.strip()
    .str.lower() == "no"
].copy()

# Reset indices for easier editing
disagreements.reset_index(drop=True, inplace=True)

# Create Part 2 columns
disagreements["ResolutionType(AuthorKept ValidatorKept/Compromise)"] = ""
disagreements["PostDiscussAgreementstatus(Yes/No)"] = ""

print(f"Disagreements requiring discussion: {len(disagreements)}")

display(
    disagreements[
        [
            "WOCProjectID",
            "Field",
            "AuthorValue",
            "ValidatorValue",
            "KeyEvidence"
        ]
    ]
)

Disagreements requiring discussion: 10

,WOCProjectID,Field,AuthorValue,ValidatorValue,KeyEvidence
0,microprediction_timemachines,WhyRecovered,Maintainer returned to fix CI workflows and re...,"Maintainer returned to fix CI workflows, refre...",Longest gap: 2023-07 to 2024-09 (15 months). C...
1,ntustison_crosslong,ActivityPattern,declining,Stopped,Total commits: 311. Timeline: 2016-06-29 to 20...
2,patwie_cppnumericalsolvers,ActivityPattern,U-shaped,Steady,Total commits: 335. Timeline: 2014-05-29 to 20...
3,simplenlg_simplenlg,ActivityPattern,irregular,Declining,Total commits: 136. Timeline: 2014-08-20 to 20...
4,smtorg_smt,ActivityPattern,steady,Rising,Total commits: 3821. Timeline: 2016-11-08 to 2...
5,stan-dev_projpred,ActivityPattern,declining,Steady,Total commits: 6804. Timeline: 2016-06-16 to 2...
6,afeinstein20_eleanor,RecentThemes,Bug fixes: Other,"Bug Fixes, Merges",Recent commit messages: 2025-08-26: Merge dc5c...
7,algebraicjulia_catlab.jl,RecentThemes,Dependency updates:Other,"Dependency Updates, Merges",Recent commit messages: 2025-09-29: FEEDBACK: ...
8,ntustison_crosslong,RecentThemes,Other,Documentation Updates,Recent commit messages: 2025-07-16: Update REA...
9,patwie_cppnumericalsolvers,RecentThemes,Other: Bug fixes,"Bug Fixes, Dependency Updates",Recent commit messages: 2025-07-27: Add CITATI...

In [3]:
resolution_columns = [
    "WOCProjectID",
    "ProjectOwnerNetID",
    "ValidatorNetID",
    "Field",
    "AuthorValue",
    "ValidatorValue",
    "AdjudicatedValue",
    "ResolutionType(AuthorKept ValidatorKept/Compromise)",
    "PostDiscussAgreementstatus(Yes/No)",
    "KeyEvidence",
    "Comments"
]

resolution_df = disagreements.reindex(columns=resolution_columns)

RESOLUTION_FILE = Path(
    f"{MY_NETID}_disagreement_resolution.csv"
)

resolution_df.to_csv(RESOLUTION_FILE, index=False)

print(f"Created: {RESOLUTION_FILE}")
print(f"Rows: {len(resolution_df)}")

display(resolution_df)

Created: cdamron3_disagreement_resolution.csv
Rows: 11

,WOCProjectID,ProjectOwnerNetID,ValidatorNetID,Field,AuthorValue,ValidatorValue,AdjudicatedValue,ResolutionType(AuthorKept ValidatorKept/Compromise),PostDiscussAgreementstatus(Yes/No),KeyEvidence,Comments
0,microprediction_timemachines,ncash3,cdamron3,WhyRecovered,Maintainer returned to fix CI workflows and re...,"Maintainer returned to fix CI workflows, refre...",,,,Longest gap: 2023-07 to 2024-09 (15 months). C...,
1,ntustison_crosslong,ncash3,cdamron3,ActivityPattern,declining,Stopped,,,,Total commits: 311. Timeline: 2016-06-29 to 20...,
2,patwie_cppnumericalsolvers,ncash3,cdamron3,ActivityPattern,U-shaped,Steady,,,,Total commits: 335. Timeline: 2014-05-29 to 20...,
3,simplenlg_simplenlg,ncash3,cdamron3,ActivityPattern,irregular,Declining,,,,Total commits: 136. Timeline: 2014-08-20 to 20...,
4,smtorg_smt,ncash3,cdamron3,ActivityPattern,steady,Rising,,,,Total commits: 3821. Timeline: 2016-11-08 to 2...,
5,stan-dev_projpred,ncash3,cdamron3,ActivityPattern,declining,Steady,,,,Total commits: 6804. Timeline: 2016-06-16 to 2...,
6,simplenlg_simplenlg,ncash3,cdamron3,Currentstatus,Inactive,Inactive,,,,"Commits between April 1 and September 30, 2025...",
7,afeinstein20_eleanor,ncash3,cdamron3,RecentThemes,Bug fixes: Other,"Bug Fixes, Merges",,,,Recent commit messages: 2025-08-26: Merge dc5c...,
8,algebraicjulia_catlab.jl,ncash3,cdamron3,RecentThemes,Dependency updates:Other,"Dependency Updates, Merges",,,,Recent commit messages: 2025-09-29: FEEDBACK: ...,
9,ntustison_crosslong,ncash3,cdamron3,RecentThemes,Other,Documentation Updates,,,,Recent commit messages: 2025-07-16: Update REA...,
10,patwie_cppnumericalsolvers,ncash3,cdamron3,RecentThemes,Other: Bug fixes,"Bug Fixes, Dependency Updates",,,,Recent commit messages: 2025-07-27: Add CITATI...,

In [ ]:
# ==========================================
# DISCUSSION RESULTS
# ==========================================
# Fill these in AFTER talking to your teammate.
#
# adjudicated: Final agreed-upon classification
# comments: Explanation of how disagreement was resolved
# post_agreement: "Yes" or "No"
#
# Leave values blank until your discussion.

discussion_results = {

    ("microprediction_timemachines", "WhyRecovered"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("ntustison_crosslong", "ActivityPattern"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("patwie_cppnumericalsolvers", "ActivityPattern"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("simplenlg_simplenlg", "ActivityPattern"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("smtorg_smt", "ActivityPattern"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("stan-dev_projpred", "ActivityPattern"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("afeinstein20_eleanor", "RecentThemes"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("algebraicjulia_catlab.jl", "RecentThemes"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("ntustison_crosslong", "RecentThemes"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    },

    ("patwie_cppnumericalsolvers", "RecentThemes"): {
        "adjudicated": "",
        "comments": "",
        "post_agreement": ""
    }
}

In [ ]:
def normalize(value):
    return " ".join(str(value).strip().lower().split())


def get_resolution_type(author, validator, adjudicated):

    if not str(adjudicated).strip():
        return ""

    final = normalize(adjudicated)

    if final == normalize(author):
        return "AuthorKept"

    if final == normalize(validator):
        return "ValidatorKept"

    return "Compromise"

In [ ]:
# Load fresh copies so repeated runs don't duplicate changes
df = pd.read_csv(VALIDATION_FILE, keep_default_na=False)

resolution_df = pd.read_csv(
    RESOLUTION_FILE,
    keep_default_na=False
)

resolution_type_col = (
    "ResolutionType(AuthorKept ValidatorKept/Compromise)"
)

post_agreement_col = (
    "PostDiscussAgreementstatus(Yes/No)"
)

for (project, field), result in discussion_results.items():

    final_value = result["adjudicated"].strip()
    comments = result["comments"].strip()
    post_agreement = result["post_agreement"].strip()

    # Don't update unfinished discussions
    if not final_value:
        continue

    # Locate matching disagreement
    mask = (
        (resolution_df["WOCProjectID"] == project) &
        (resolution_df["Field"] == field)
    )

    if not mask.any():
        raise ValueError(
            f"Disagreement not found: {project}, {field}"
        )

    author = resolution_df.loc[mask, "AuthorValue"].iloc[0]
    validator = resolution_df.loc[mask, "ValidatorValue"].iloc[0]

    resolution_type = get_resolution_type(
        author,
        validator,
        final_value
    )

    # Update resolution CSV
    resolution_df.loc[mask, "AdjudicatedValue"] = final_value
    resolution_df.loc[mask, resolution_type_col] = resolution_type
    resolution_df.loc[mask, post_agreement_col] = post_agreement
    resolution_df.loc[mask, "Comments"] = comments

    # Update original validation log
    original_mask = (
        (df["WOCProjectID"] == project) &
        (df["Field"] == field)
    )

    df.loc[original_mask, "AdjudicatedValue"] = final_value
    df.loc[original_mask, "Comments"] = comments

# Save updated files
resolution_df.to_csv(RESOLUTION_FILE, index=False)

df.to_csv(VALIDATION_FILE, index=False)

print("Updated validation log and disagreement resolution CSV.")

In [ ]:
EXAMPLES_FILE = Path(
    f"{MY_NETID}_disagreement_examples.md"
)

# Reload the latest resolution data
resolution_df = pd.read_csv(
    RESOLUTION_FILE,
    keep_default_na=False
)

markdown = f"""# MiniProject3 Disagreement Examples

**Project Owner:** {TEAMMATE_NETID}

**Validator:** {MY_NETID}

This document records examples of disagreements identified
during the qualitative validation of MiniProject2.

"""

# Choose three examples from different fields
example_keys = [
    ("microprediction_timemachines", "WhyRecovered"),
    ("ntustison_crosslong", "ActivityPattern"),
    ("afeinstein20_eleanor", "RecentThemes")
]

for i, (project, field) in enumerate(example_keys, start=1):

    match = resolution_df[
        (resolution_df["WOCProjectID"] == project) &
        (resolution_df["Field"] == field)
    ]

    if match.empty:
        continue

    row = match.iloc[0]

    markdown += f"""
## Example {i}: {project}

**Field:** {field}

**Parties:** {TEAMMATE_NETID} (Project Owner) and {MY_NETID} (Validator)

**AuthorValue:** {row['AuthorValue']}

**ValidatorValue:** {row['ValidatorValue']}

**KeyEvidence:** {row['KeyEvidence']}

**AdjudicatedValue:** {row['AdjudicatedValue'] or 'PENDING DISCUSSION'}

**ResolutionType:** {row['ResolutionType(AuthorKept ValidatorKept/Compromise)'] or 'PENDING DISCUSSION'}

**Discussion and Resolution:**

{row['Comments'] or 'TODO: Describe the evidence considered, the discussion, and how the final classification was reached.'}

---
"""

EXAMPLES_FILE.write_text(markdown, encoding="utf-8")

print(f"Created: {EXAMPLES_FILE}")

In [ ]:

resolution_df = pd.read_csv(
    RESOLUTION_FILE,
    keep_default_na=False
)

total = len(resolution_df)

completed = (
    (resolution_df["AdjudicatedValue"].str.strip() != "") &
    (resolution_df["Comments"].str.strip() != "") &
    (resolution_df["PostDiscussAgreementstatus(Yes/No)"]
        .str.strip()
        .isin(["Yes", "No"]))
).sum()

print("PART 2 PROGRESS")
print("=" * 40)
print(f"Total disagreements: {total}")
print(f"Completed discussions: {completed}")
print(f"Remaining discussions: {total - completed}")

display(
    resolution_df[
        resolution_df["AdjudicatedValue"].str.strip() == ""
    ][
        ["WOCProjectID", "Field", "AuthorValue", "ValidatorValue"]
    ]
)